import { test, expect } from '@playwright/test'

test('RTL desktop and mobile: authentication, demo, purchases, editing, filtering, persistence, roles and logout', async ({ page }) => {
  const errors:string[]=[]
  page.on('pageerror',e=>errors.push(e.message))
  await page.goto('/')
  await expect(page.getByRole('heading',{name:'خوش آمدید.'})).toBeVisible()
  await page.screenshot({path:'qa/login-desktop.png',fullPage:true})
  await page.getByLabel('نام کاربری',{exact:true}).fill('admin')
  await page.getByLabel('رمز عبور',{exact:true}).fill('wrong-password')
  await page.getByRole('button',{name:'ورود به سامانه',exact:true}).click()
  await expect(page.getByRole('alert')).toContainText('صحیح نیست')
  await page.getByLabel('رمز عبور',{exact:true}).fill('Fleet-QA-Password-2026')
  await page.getByRole('button',{name:'ورود به سامانه',exact:true}).click()
  await expect(page.getByRole('heading',{name:'همهٔ ناوگان، در یک نگاه.'})).toBeVisible()
  await page.getByRole('button',{name:'مشاهده داده نمایشی',exact:true}).click()
  await expect(page.getByText('حالت نمایشی · این اطلاعات ساختگی است و آمار واقعی ماهکس نیست.')).toBeVisible()
  await expect(page.locator('.stat-value').first()).toContainText('۱۲')
  await expect(page.locator('.recharts-surface').first()).toBeVisible()
  await expect(page.locator('.recharts-pie-sector')).toHaveCount(4)
  await expect(page.locator('.recharts-bar-rectangle').first()).toBeVisible()
  if(await page.getByRole('button',{name:'بستن پیام',exact:true}).count())await page.getByRole('button',{name:'بستن پیام',exact:true}).click()
  await page.screenshot({path:'qa/dashboard-desktop.png',fullPage:true})
  await page.getByRole('button',{name:'ثبت موتورسیکلت',exact:true}).click()
  const dialog=page.getByRole('dialog')
  await expect(dialog).toBeVisible()
  await dialog.getByLabel('شناسه',{exact:false}).first().fill('QA-M001')
  await dialog.getByLabel('مدل موتور',{exact:false}).fill('موتور تست خرید')
  await dialog.getByLabel('نوع موتور',{exact:false}).selectOption('gasoline')
  await dialog.getByLabel('ناوگان',{exact:false}).selectOption('demo-fleets-1')
  await dialog.getByLabel('پلاک',{exact:true}).fill('QA-123')
  await dialog.getByLabel('شماره شاسی / VIN',{exact:true}).fill('QA-VIN-001')
  await dialog.getByLabel('مبلغ خرید (تومان)',{exact:false}).fill('175000000')
  await dialog.getByLabel('تاریخ خرید',{exact:true}).fill('2026-09-21')
  await dialog.getByLabel('فروشنده / تأمین‌کننده',{exact:true}).fill('فروشنده آزمون')
  await dialog.getByLabel('شماره فاکتور',{exact:true}).fill('QA-INV-001')
  await page.screenshot({path:'qa/purchase-form.png',fullPage:true})
  await dialog.getByRole('button',{name:'ذخیره اطلاعات',exact:true}).click()
  await expect(dialog).not.toBeVisible()
  await page.getByLabel('جستجو در فهرست',{exact:true}).fill('QA-M001')
  await expect(page.locator('tbody tr')).toHaveCount(1)
  await expect(page.locator('tbody')).toContainText('موتور تست خرید')
  await page.getByRole('button',{name:'ویرایش QA-M001',exact:true}).click()
  await dialog.getByLabel('مدل موتور',{exact:false}).fill('موتور تست اصلاح‌شده')
  await dialog.getByRole('button',{name:'ذخیره اطلاعات',exact:true}).click()
  await expect(dialog).not.toBeVisible()
  await page.reload()
  await page.getByLabel('جستجو در فهرست',{exact:true}).fill('QA-M001')
  await expect(page.locator('tbody')).toContainText('موتور تست اصلاح‌شده')
  await page.getByRole('button',{name:'مشاهده QA-M001',exact:true}).click()
  await expect(dialog).toContainText('۱۷۵٬۰۰۰٬۰۰۰')
  await expect(dialog).toContainText('QA-INV-001')
  await dialog.getByRole('button',{name:'بستن',exact:true}).first().click()
  const downloaded=page.waitForEvent('download')
  await page.getByRole('button',{name:'خروجی CSV',exact:true}).click()
  expect((await downloaded).suggestedFilename()).toBe('vehicles-report.csv')
  await page.getByRole('navigation').getByRole('button',{name:'باتری‌ها',exact:true}).click()
  await expect(page.getByRole('heading',{name:'باتری‌ها',exact:true})).toBeVisible()
  await page.screenshot({path:'qa/batteries-desktop.png',fullPage:true})
  await page.getByRole('navigation').getByRole('button',{name:'گزارش عملکرد',exact:true}).click()
  await expect(page.getByRole('heading',{name:'عملکرد مراکز توزیع',exact:true})).toBeVisible()
  await page.getByLabel('بازه گزارش',{exact:true}).selectOption('14')
  await page.screenshot({path:'qa/reports-desktop.png',fullPage:true})
  for(const name of ['ناوگان','مدیریت شارژ','مأموریت‌ها','پشتیبانی و SLA','مراکز توزیع','رانندگان','شارژرها','شیفت‌ها','کنترل پیش از شیفت','کارکرد روزانه','آمادگی پایلوت','ارائه راهبردی']) {
    await page.getByRole('navigation').getByRole('button',{name,exact:true}).click()
    await expect(page.locator('main h1')).toBeVisible()
    expect(await page.locator('main').innerText()).not.toContain('undefined')
  }
  await page.getByRole('button',{name:'اسلاید بعد',exact:true}).click()
  await expect(page.locator('.presentation-toolbar')).toContainText('قدرت مهندسی مپنا')
  await page.getByRole('navigation').getByRole('button',{name:'تنظیمات',exact:true}).click()
  await page.getByRole('button',{name:'کاربران و نقش‌ها',exact:true}).click()
  await page.getByRole('button',{name:'افزودن کاربر',exact:true}).click()
  await dialog.getByLabel('نام کامل',{exact:true}).fill('کاربر مشاهده‌گر')
  await dialog.getByLabel('نام کاربری',{exact:true}).fill('qa-viewer')
  await dialog.getByLabel('رمز عبور',{exact:true}).fill('Viewer-QA-Password-2026')
  await dialog.getByRole('button',{name:'ذخیره کاربر',exact:true}).click()
  await expect(dialog).not.toBeVisible()
  await page.getByRole('navigation').getByRole('button',{name:'داشبورد',exact:true}).click()
  await page.setViewportSize({width:390,height:844})
  await expect(page.getByRole('button',{name:'باز کردن فهرست',exact:true})).toBeVisible()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
  if(await page.getByRole('button',{name:'بستن پیام',exact:true}).count())await page.getByRole('button',{name:'بستن پیام',exact:true}).click()
  await page.screenshot({path:'qa/dashboard-mobile.png',fullPage:true})
  await page.getByRole('button',{name:'باز کردن فهرست',exact:true}).click()
  await page.getByRole('navigation').getByRole('button',{name:'موتورسیکلت‌ها',exact:true}).click()
  await expect(page.getByRole('heading',{name:'موتورسیکلت‌ها',exact:true})).toBeVisible()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
  await page.screenshot({path:'qa/vehicles-mobile.png',fullPage:true})
  await page.getByRole('button',{name:'باز کردن فهرست',exact:true}).click()
  await page.getByRole('button',{name:'خروج از حساب',exact:true}).click()
  await expect(page.getByRole('heading',{name:'خوش آمدید.'})).toBeVisible()
  await page.getByLabel('نام کاربری',{exact:true}).fill('qa-viewer')
  await page.getByLabel('رمز عبور',{exact:true}).fill('Viewer-QA-Password-2026')
  await page.getByRole('button',{name:'ورود به سامانه',exact:true}).click()
  await expect(page.getByRole('heading',{name:'همهٔ ناوگان، در یک نگاه.'})).toBeVisible()
  await expect(page.getByRole('button',{name:'ثبت موتورسیکلت',exact:true})).toHaveCount(0)
  expect(errors).toEqual([])
})
