import { test, expect } from '@playwright/test'

test('MAPNA login: native wheel journey, parallax, theme, motion controls and real authentication', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'خوش آمدید.' })).toBeVisible()
  await expect(page).toHaveTitle('مپنا | مدیریت هوشمند ناوگان')
  await expect(page.getByRole('img', { name: 'گروه مپنا | MAPNA GROUP', exact: true })).toBeVisible()
  await page.evaluate(() => document.fonts.ready)
  const root = page.locator('.login-experience')
  const motor = page.locator('.login-motor-wrap')
  const card = page.locator('.access-card')
  const formY = (await card.boundingBox())!.y
  await page.mouse.move(170, 440)
  const initialTransform = await motor.evaluate(element => getComputedStyle(element).transform)
  await page.mouse.move(680, 520, { steps: 10 })
  await expect.poll(() => motor.evaluate(element => getComputedStyle(element).transform)).not.toBe(initialTransform)
  await page.screenshot({ path: 'qa/mapna-login-desktop.png', animations: 'disabled' })
  await page.getByLabel('نام کاربری', { exact: true }).fill('admin')
  await page.getByLabel('رمز عبور', { exact: true }).fill('Fleet-QA-Password-2026')
  await page.mouse.move(260, 600)
  await page.mouse.wheel(0, 760)
  await expect(root).toHaveAttribute('data-phase', '1')
  await expect(page.getByRole('heading', { name: /انرژیِ امروز/ })).toBeVisible()
  await expect(page.locator('.login-charger')).toHaveCSS('opacity', '1')
  expect(Math.abs((await card.boundingBox())!.y - formY)).toBeLessThan(2)
  await expect(page.getByLabel('رمز عبور', { exact: true })).toHaveValue('Fleet-QA-Password-2026')
  await page.getByRole('button', { name: 'نمای شب', exact: true }).click()
  await expect(root).toHaveAttribute('data-night', 'true')
  await page.screenshot({ path: 'qa/mapna-login-energy-night.png', animations: 'disabled' })
  await page.getByRole('button', { name: 'آشنایی با مدیریت انرژی' }).click()
  await expect(page.getByRole('status')).toContainText('انرژی در زمان درست')
  await page.getByRole('button', { name: 'بستن توضیحات', exact: true }).click()
  await page.mouse.move(260, 600)
  await page.mouse.wheel(0, 650)
  await expect(root).toHaveAttribute('data-phase', '2')
  await expect(page.getByRole('button', { name: 'ورود به سامانه', exact: true })).toBeInViewport()
  await page.getByRole('button', { name: 'نمای روز', exact: true }).click()
  await page.screenshot({ path: 'qa/mapna-login-connected.png', animations: 'disabled' })
  await page.getByRole('button', { name: 'توقف حرکت‌ها', exact: true }).click()
  await expect(root).toHaveAttribute('data-motion', 'off')
  await expect(motor).toHaveCSS('transform', 'none')
  await expect(page.locator('.login-motor')).toHaveCSS('animation-name', 'none')
  // The sticky composition must also fit a common laptop viewport.
  await page.setViewportSize({ width: 1366, height: 768 })
  await expect(page.getByRole('button', { name: 'ورود به سامانه', exact: true })).toBeInViewport()
  await expect(page.getByRole('navigation', { name: 'صحنه‌های صفحه ورود' })).toBeInViewport()
  const sceneBox = (await page.locator('.login-scene').boundingBox())!
  const headingBox = (await page.locator('.login-scene-heading').boundingBox())!
  expect(headingBox.x + headingBox.width).toBeLessThanOrEqual(sceneBox.x + sceneBox.width + 1)
  expect(headingBox.x).toBeGreaterThanOrEqual(sceneBox.x - 1)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: 'qa/mapna-login-laptop.png', animations: 'disabled' })
  await page.getByRole('navigation', { name: 'صحنه‌های صفحه ورود' }).getByRole('button', { name: /حرکت/ }).click()
  await expect(root).toHaveAttribute('data-phase', '0')
  await page.getByRole('button', { name: 'نمایش رمز', exact: true }).click()
  await expect(page.getByLabel('رمز عبور', { exact: true })).toHaveAttribute('type', 'text')
  await page.getByRole('button', { name: 'پنهان کردن رمز', exact: true }).click()
  await page.getByLabel('رمز عبور', { exact: true }).press('Enter')
  await expect(page.getByRole('heading', { name: 'همهٔ ناوگان، در یک نگاه.' })).toBeVisible()
  expect(await page.evaluate(() => window.scrollY)).toBe(0)
  await expect(page.locator('.workspace-label')).toContainText('مپنا')
  expect(errors).toEqual([])
})

test('MAPNA login: compact/mobile layout, keyboard controls, reduced motion and recoverable errors', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  const root = page.locator('.login-experience')
  await expect(root).toHaveAttribute('data-motion', 'off')
  await expect(page.getByRole('button', { name: 'ورود به سامانه', exact: true })).toBeInViewport()
  await expect(page.getByRole('button', { name: 'فعال کردن حرکت‌ها', exact: true })).toBeDisabled()
  await page.evaluate(() => document.fonts.ready)
  await page.screenshot({ path: 'qa/mapna-login-mobile.png', fullPage: true, animations: 'disabled' })
  const nav = page.getByRole('navigation', { name: 'صحنه‌های صفحه ورود' })
  for (const [index, label] of ['حرکت', 'انرژی', 'مدیریت'].entries()) {
    const button = nav.getByRole('button', { name: new RegExp(label) })
    await button.focus()
    await button.press('Enter')
    await expect(root).toHaveAttribute('data-phase', String(index))
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  }
  // Short desktop windows use normal scrolling while retaining scene controls.
  await page.setViewportSize({ width: 1280, height: 640 })
  await nav.getByRole('button', { name: /حرکت/ }).click()
  await page.locator('.login-scene').hover()
  await page.mouse.wheel(0, 180)
  await expect(root).toHaveAttribute('data-phase', '1')
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByLabel('نام کاربری', { exact: true }).fill('admin')
  await page.getByLabel('رمز عبور', { exact: true }).fill('wrong-password')
  await page.getByRole('button', { name: 'ورود به سامانه', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('صحیح نیست')
  await expect(page.getByLabel('نام کاربری', { exact: true })).toHaveValue('admin')
  await page.getByLabel('رمز عبور', { exact: true }).fill('Fleet-QA-Password-2026')
  await page.getByRole('button', { name: 'ورود به سامانه', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'همهٔ ناوگان، در یک نگاه.' })).toBeVisible()
})
