import { test, expect } from '@playwright/test'

test('interactive presentation: chapters, original slides, motion controls and responsive layout', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/#presentation')
  await page.getByLabel('نام کاربری', { exact: true }).fill('admin')
  await page.getByLabel('رمز عبور', { exact: true }).fill('Fleet-QA-Password-2026')
  await page.getByRole('button', { name: 'ورود به سامانه', exact: true }).click()
  await expect(page.getByRole('heading', { name: /آیندهٔ ناوگان،/ })).toBeVisible()
  await page.evaluate(() => document.fonts.ready)
  await expect(page.locator('.story-cover-bike')).toBeVisible()
  await page.screenshot({ path: 'qa/presentation-cover-desktop.png', fullPage: true, animations: 'disabled' })
  const nav = page.getByRole('navigation', { name: 'فصل‌های ارائه' })
  await page.getByRole('button', { name: 'روایت را آغاز کنید' }).click()
  await page.getByRole('button', { name: 'هزینهٔ توقف', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'توقف، چقدر هزینه دارد؟' })).toBeVisible()
  await nav.getByRole('button', { name: /خدمت یکپارچه/ }).click()
  await page.getByRole('button', { name: 'انرژی', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'باتری و انرژی', exact: true })).toBeVisible()
  await page.screenshot({ path: 'qa/presentation-service-desktop.png', fullPage: true, animations: 'disabled' })
  await nav.getByRole('button', { name: /یک روز کاری/ }).click()
  const initialBikeX = (await page.locator('.story-road-bike').boundingBox())!.x
  await page.getByRole('button', { name: /بین مأموریت‌ها/ }).click()
  await expect(page.getByText('انرژی برای ادامهٔ مسیر', { exact: true })).toBeVisible()
  await expect.poll(async () => (await page.locator('.story-road-bike').boundingBox())!.x).toBeLessThan(initialBikeX - 100)
  await nav.getByRole('button', { name: /منطق اقتصادی/ }).click()
  await page.getByRole('button', { name: /توقف عملیات/ }).click()
  await expect(page.getByText(/زمان خارج از سرویس و مأموریت‌های ازدست‌رفته/)).toBeVisible()
  await nav.getByRole('button', { name: /پایلوت ناوگان/ }).click()
  await page.getByRole('button', { name: 'تعویض باتری', exact: true }).click()
  await expect(page.getByAltText('تصویر مفهومی ایستگاه تعویض باتری')).toBeVisible()
  await page.screenshot({ path: 'qa/presentation-pilot-desktop.png', fullPage: true, animations: 'disabled' })
  await page.getByRole('button', { name: /آمادگی عملیات/ }).click()
  await expect(page.getByText('رانندهٔ آموزش‌دیده، شیفت مشخص و مسئول پاسخ‌گو.')).toBeVisible()
  await nav.getByRole('button', { name: /مسیر آینده/ }).click()
  await page.getByRole('button', { name: 'مرور اسلایدهای اصلی' }).click()
  await expect(page.locator('.presentation-toolbar')).toContainText('افق توسعه')
  await page.getByRole('button', { name: 'اسلاید بعد', exact: true }).click()
  await expect(page.locator('.slide-image')).toHaveAttribute('src', '/media/strategy-14.jpg')
  await expect(page.getByRole('button', { name: 'اسلاید بعد', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'روایت تعاملی', exact: true }).click()
  await page.getByRole('button', { name: 'بازگشت به آغاز' }).click()
  await page.getByRole('button', { name: 'خاموش کردن حرکت‌ها' }).click()
  await expect(page.locator('.strategy-experience')).toHaveClass(/motion-off/)
  await page.getByRole('button', { name: 'شروع پخش خودکار' }).click()
  await expect(page.getByRole('button', { name: 'توقف پخش خودکار' })).toBeVisible()
  await expect(page.getByRole('heading', { name: /تعویض موتور نیست/ })).toBeVisible({ timeout: 17000 })
  await page.getByRole('button', { name: 'توقف پخش خودکار' }).click()
  await page.getByRole('button', { name: 'فصل بعد', exact: true }).focus()
  await page.keyboard.press('Home')
  await expect(page.getByRole('heading', { name: /آیندهٔ ناوگان،/ })).toBeVisible()
  await page.getByRole('button', { name: 'نمایش تمام‌صفحه' }).click()
  await expect(page.getByRole('button', { name: 'خروج از تمام‌صفحه' })).toBeVisible()
  await page.screenshot({ path: 'qa/presentation-fullscreen.png', fullPage: true, animations: 'disabled' })
  await page.getByRole('button', { name: 'خروج از تمام‌صفحه' }).click()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: 'qa/presentation-cover-mobile.png', fullPage: true, animations: 'disabled' })
  const names = ['افق برقی','مسئلهٔ عملیات','خدمت یکپارچه','یک روز کاری','منطق اقتصادی','پایلوت ناوگان','مسیر آینده']
  for (const name of names) {
    await nav.getByRole('button', { name: new RegExp(name) }).click()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  }
  await nav.getByRole('button', { name: /پایلوت ناوگان/ }).click()
  await page.screenshot({ path: 'qa/presentation-pilot-mobile.png', fullPage: true, animations: 'disabled' })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await expect(page.locator('.strategy-experience')).toHaveClass(/motion-off/)
  expect(errors).toEqual([])
})
