import { useCallback, useEffect, useState } from 'react'
import type { Bootstrap, User } from './types'
import { api, setCsrf } from './api'
import { Icon, Logo, ErrorBox } from './components'
import { date, fa } from './utils'
import Records from './Records'
import { Dashboard, Reports } from './Dashboard'
import Settings from './Settings'
import Presentation from './Presentation'
import FleetBanner from './FleetBanner'

const navigation=[{label:'مرکز عملیات',items:[['dashboard','داشبورد','LayoutDashboard'],['fleets','ناوگان','Truck'],['vehicles','موتورسیکلت‌ها','Bike'],['batteries','باتری‌ها','Battery'],['charges','مدیریت شارژ','Zap'],['missions','مأموریت‌ها','Flag']]},{label:'خدمات و تحلیل',items:[['incidents','خرابی‌ها','TriangleAlert'],['tickets','پشتیبانی و SLA','Headset'],['reports','گزارش عملکرد','ChartNoAxesCombined']]},{label:'مدیریت و پیکربندی',items:[['centers','مراکز توزیع','MapPin'],['drivers','رانندگان','Users'],['chargers','شارژرها','PlugZap'],['shifts','شیفت‌ها','CalendarClock'],['checks','کنترل پیش از شیفت','ClipboardCheck'],['daily_logs','کارکرد روزانه','NotebookPen'],['gates','آمادگی پایلوت','ShieldCheck'],['settings','تنظیمات','Settings'],['presentation','ارائه راهبردی','Presentation']]}]
const validPages=new Set(navigation.flatMap(g=>g.items.map(i=>i[0])))
function initialPage(){const value=window.location.hash.slice(1);return validPages.has(value)?value:'dashboard'}

export default function App(){
  const [user,setUser]=useState<User|null>(null);const [data,setData]=useState<Bootstrap|null>(null);const [booting,setBooting]=useState(true);const [loadError,setLoadError]=useState('');const [page,setPage]=useState(initialPage);const [center,setCenter]=useState('');const [query,setQuery]=useState('');const [mobileMenu,setMobileMenu]=useState(false);const [refreshing,setRefreshing]=useState(false);const [toast,setToast]=useState<{message:string;error:boolean;id:number}|null>(null);const [createNext,setCreateNext]=useState(false)
  const notify=useCallback((message:string,error=false)=>setToast({message,error,id:Date.now()}),[])
  const reload=useCallback(async()=>{const result=await api<Bootstrap>('/bootstrap');setData(result);setLoadError('')},[])
  const navigate=useCallback((next:string)=>{window.location.hash=next;setPage(next);setQuery('');setMobileMenu(false);window.scrollTo({top:0})},[])
  const afterLogin=async(value:{user:User;csrf:string})=>{setUser(value.user);setCsrf(value.csrf);await reload()}
  const initialize=useCallback(async()=>{setBooting(true);setLoadError('');try{const result=await api<{user:User;csrf:string}>('/auth/me');setUser(result.user);setCsrf(result.csrf);await reload()}catch(e){if((e as Error).message!=='لطفاً وارد حساب کاربری شوید.')setLoadError((e as Error).message)}finally{setBooting(false)}},[reload])
  useEffect(()=>{void initialize();const expired=()=>{setUser(null);setData(null);setCsrf('')};const hash=()=>{setPage(initialPage());setQuery('');setMobileMenu(false)};window.addEventListener('session-expired',expired);window.addEventListener('hashchange',hash);return()=>{window.removeEventListener('session-expired',expired);window.removeEventListener('hashchange',hash)}},[initialize])
  useEffect(()=>{if(!toast)return;const id=setTimeout(()=>setToast(null),5500);return()=>clearTimeout(id)},[toast])
  useEffect(()=>{if(data&&center&&!data.records.centers.some(c=>c.id===center))setCenter('')},[data,center])
  const onCreateOpened=useCallback(()=>setCreateNext(false),[])
  const create=(kind:string)=>{navigate(kind);setCreateNext(true)}
  const refresh=async()=>{setRefreshing(true);try{await reload();notify('اطلاعات به‌روز شد.')}catch(e){notify((e as Error).message,true)}finally{setRefreshing(false)}}
  const logout=async()=>{try{await api('/auth/logout','POST');setCsrf('');setUser(null);setData(null);setQuery('');setCenter('');navigate('dashboard')}catch(e){notify((e as Error).message,true)}}
  if(booting)return <div className="loading-screen"><Logo dark/><Icon name="LoaderCircle" size={26} className="spin"/><p>در حال اتصال به سامانه…</p></div>
  if(!user)return <Login onLogin={afterLogin} loadError={loadError}/>
  if(!data)return <div className="loading-screen"><ErrorBox message={loadError||'اطلاعات بارگذاری نشد.'}/><button className="button primary" onClick={()=>void initialize()}>تلاش مجدد</button><button className="button" onClick={logout}>خروج</button></div>
  const title=data.catalog[page]?.label||{dashboard:'داشبورد عملیات',reports:'گزارش‌های عملکرد',settings:'تنظیمات سامانه',presentation:'ارائه راهبردی مپنا'}[page]||'داشبورد'
  const openIncidents=data.records.incidents.filter(i=>!['closed','resolved'].includes(String(i.status))).length
  const isEmpty=!Object.values(data.records).some(r=>r.length)
  return <div className="app-shell">
    {mobileMenu&&<button className="sidebar-scrim" aria-label="بستن فهرست" onClick={()=>setMobileMenu(false)}/>}
    <aside className={'sidebar '+(mobileMenu?'is-open':'')}><div className="sidebar-brand"><Logo/></div><div className="workspace-label"><span className="workspace-avatar">م</span><div><strong>{String(data.settings.organization)}</strong><small>فضای کاری ناوگان</small></div><Icon name="ChevronLeft" size={15}/></div><nav aria-label="منوی اصلی">{navigation.map(group=><div className="nav-group" key={group.label}><div className="nav-label">{group.label}</div>{group.items.map(([id,name,icon])=><button key={id} className={'nav-item '+(page===id?'active':'')} onClick={()=>navigate(id)} aria-current={page===id?'page':undefined}><Icon name={icon} size={19}/><span>{name}</span>{id==='incidents'&&openIncidents>0&&<b>{fa(openIncidents)}</b>}{id==='dashboard'&&page===id&&<i/>}</button>)}</div>)}</nav><div className="sidebar-bottom"><div className="local-status"><i/>سامانه ناوگان<span>v1.1</span></div><button className="nav-item logout" onClick={logout}><Icon name="LogOut" size={18}/><span>خروج از حساب</span></button></div></aside>
    <div className="main-shell"><header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-toggle" aria-label="باز کردن فهرست" onClick={()=>setMobileMenu(true)}><Icon name="Menu"/></button><span>فضای کاری</span><Icon name="ChevronLeft" size={14}/><b>{title}</b></div><div className="topbar-actions"><span className="today"><Icon name="CalendarClock" size={16}/>{date(new Date().toISOString())}</span><button className="notification-button icon-button" aria-label="نمایش هشدارها" onClick={()=>navigate('incidents')}><Icon name="Bell" size={20}/>{openIncidents>0&&<i/>}</button><div className="topbar-divider"/><button className="profile-button" onClick={()=>navigate('settings')}><span className="avatar">{user.name.slice(0,1)}</span><span><strong>{user.name}</strong><small>{data.roles[user.role]}</small></span><Icon name="ChevronLeft" size={15}/></button></div></header>
    <main className={page==='presentation'?'presentation-workspace':undefined}><div className="workspace-toolbar"><div className="center-control"><Icon name="MapPin" size={17}/><select aria-label="انتخاب مرکز توزیع" value={center} onChange={e=>setCenter(e.target.value)}><option value="">همه مراکز توزیع</option>{data.records.centers.map(c=><option key={c.id} value={c.id}>{String(c.name)}</option>)}</select></div><div className="toolbar-end"><span className="sync-label"><i/>{data.demo_count>0?'داده‌های نمایشی':'اطلاعات ثبت‌شده'}</span><button className="icon-button" title="به‌روزرسانی اطلاعات" aria-label="به‌روزرسانی اطلاعات" disabled={refreshing} onClick={refresh}><Icon name="RefreshCw" size={17} className={refreshing?'spin':''}/></button></div></div>
      {data.demo_count>0&&<div className="demo-banner"><Icon name="CircleHelp" size={16}/><span>حالت نمایشی · این اطلاعات ساختگی است و آمار واقعی ماهکس نیست.</span>{user.role==='admin'&&<button onClick={()=>navigate('settings')}>مدیریت داده‌ها <Icon name="ChevronLeft" size={14}/></button>}</div>}
      {isEmpty&&user.role==='admin'&&<div className="onboarding-banner"><div><Icon name="Leaf" size={25}/><div><b>به مرکز مدیریت ناوگان خوش آمدید</b><p>از ثبت مرکز توزیع و ناوگان شروع کنید یا امکانات را با داده‌های نمایشی ببینید.</p></div></div><div className="action-row"><button className="button primary" onClick={()=>create('centers')}>ثبت اولین مرکز</button><button className="button" disabled={refreshing} onClick={async()=>{setRefreshing(true);try{await api('/demo/load','POST');await reload();notify('داده‌های نمایشی بارگذاری شد.')}catch(e){notify((e as Error).message,true)}finally{setRefreshing(false)}}}>مشاهده داده نمایشی</button></div></div>}
      {page!=='dashboard'&&<div className="page-heading"><div><span className="eyebrow">مرکز مدیریت ناوگان</span><h1>{title}</h1><p>{data.catalog[page]?.description||{reports:'تصمیم‌گیری بر پایه داده‌های عملیات',settings:'مدیریت دسترسی‌ها، شیفت‌ها و سیاست‌های عملیاتی',presentation:'مرور فایل ارائه و مسیر توسعه ناوگان'}[page]}</p></div>{data.catalog[page]&&<div className="input-icon global-search"><Icon name="Search" size={18}/><input placeholder="جستجوی سریع در این بخش…" aria-label="جستجوی سریع" value={query} onChange={e=>setQuery(e.target.value)}/></div>}</div>}
      {['vehicles','fleets','batteries','charges'].includes(page)&&<FleetBanner kind={page} onExplore={()=>navigate('presentation')}/>}
      {page==='dashboard'?<Dashboard data={data} center={center} navigate={navigate} create={create}/>:page==='reports'?<Reports data={data} center={center}/>:page==='settings'?<Settings data={data} user={user} reload={reload} notify={notify} navigate={navigate}/>:page==='presentation'?<Presentation/>:<Records key={page} kind={page} data={data} user={user} reload={reload} notify={notify} query={query} center={center} openCreate={createNext} onCreateOpened={onCreateOpened}/>}
      <footer className="page-footer"><span>ماهکس × توسن <i/> سامانه مدیریت یکپارچه ناوگان</span><span>آخرین دریافت: {date(data.server_time,true)}</span></footer>
    </main></div>{toast&&<div className={'toast '+(toast.error?'error':'')} role={toast.error?'alert':'status'}><Icon name={toast.error?'TriangleAlert':'CircleCheck'} size={20}/><span>{toast.message}</span><button className="icon-button" aria-label="بستن پیام" onClick={()=>setToast(null)}><Icon name="X" size={16}/></button></div>}
  </div>
}

function Login({onLogin,loadError}:{onLogin:(value:{user:User;csrf:string})=>Promise<void>;loadError:string}){
  const [username,setUsername]=useState('');const [password,setPassword]=useState('');const [show,setShow]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState(loadError)
  const submit=async(e:React.SubmitEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setError('');try{const result=await api<{user:User;csrf:string}>('/auth/login','POST',{username,password});await onLogin(result)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <div className="login-page"><section className="login-form-side"><Logo dark/><div className="login-form-wrap"><span className="eyebrow">مرکز مدیریت یکپارچه ناوگان</span><h1>خوش آمدید<span className="heading-dot">.</span></h1><p>برای مدیریت ناوگان و مشاهده وضعیت عملیات، وارد حساب خود شوید.</p><form onSubmit={submit}><ErrorBox message={error}/><div className="form-field"><label htmlFor="username">نام کاربری</label><div className="input-icon"><Icon name="Users" size={18}/><input id="username" name="username" autoComplete="username" required dir="ltr" placeholder="نام کاربری خود را وارد کنید" value={username} onChange={e=>setUsername(e.target.value)}/></div></div><div className="form-field"><label htmlFor="password">رمز عبور</label><div className="input-icon password-input"><Icon name="LockKeyhole" size={18}/><input id="password" name="password" autoComplete="current-password" required dir="ltr" type={show?'text':'password'} placeholder="رمز عبور خود را وارد کنید" value={password} onChange={e=>setPassword(e.target.value)}/><button type="button" className="icon-button" aria-label={show?'پنهان کردن رمز':'نمایش رمز'} onClick={()=>setShow(!show)}><Icon name={show?'EyeOff':'Eye'} size={18}/></button></div></div><button type="submit" className="button primary login-submit" disabled={busy}>{busy?'در حال ورود…':'ورود به سامانه'}<Icon name={busy?'LoaderCircle':'ArrowLeft'} size={19} className={busy?'spin':''}/></button></form><div className="login-help"><Icon name="ShieldCheck" size={18}/><span>حساب کاربری توسط مدیر سامانه ایجاد می‌شود.</span></div></div><footer>ماهکس × توسن <span>نسخه وب · ۱.۱</span></footer></section><section className="login-story"><div className="story-kicker"><i/>حرکت به سوی فردایی پایدار</div><h2>ناوگان آماده.<br/>عملیات پیوسته.<br/><span>آینده‌ای برقی.</span></h2><p>از اولین خرید تا آخرین مأموریت؛<br/>تصویری روشن از هر موتورسیکلت، باتری و مسیر.</p><div className="mobility-illustration"><img src="/media/presentation/motor-electric-side.webp" alt="تصویر مفهومی موتورسیکلت برقی حمل مرسوله"/><span className="image-tag"><Icon name="Zap" size={15}/>تحرک برقی، مدیریت هوشمند</span></div><div className="story-features"><span><Icon name="Bike" size={18}/>مدیریت ناوگان</span><span><Icon name="Battery" size={18}/>پایش انرژی</span><span><Icon name="Headset" size={18}/>پشتیبانی یکپارچه</span></div><small className="image-credit">تصویر مفهومی ناوگان برقی</small></section></div>
}
