import { lazy, Suspense, useCallback, useEffect, useState } from 'react'
import type { Bootstrap, User } from './types'
import { api, setCsrf } from './api'
import { Icon, Logo, ErrorBox } from './components'
import { date, fa } from './utils'
import FleetBanner from './FleetBanner'
import Login from './Login'

// Keep charts and management screens out of the interactive login's initial download.
const Records = lazy(() => import('./Records'))
const Dashboard = lazy(() => import('./Dashboard').then(module => ({ default: module.Dashboard })))
const Reports = lazy(() => import('./Dashboard').then(module => ({ default: module.Reports })))
const Settings = lazy(() => import('./Settings'))
const Presentation = lazy(() => import('./Presentation'))

const navigation=[{label:'مرکز عملیات',items:[['dashboard','داشبورد','LayoutDashboard'],['fleets','ناوگان','Truck'],['vehicles','موتورسیکلت‌ها','Bike'],['batteries','باتری‌ها','Battery'],['charges','مدیریت شارژ','Zap'],['missions','مأموریت‌ها','Flag']]},{label:'خدمات و تحلیل',items:[['incidents','خرابی‌ها','TriangleAlert'],['tickets','پشتیبانی و SLA','Headset'],['reports','گزارش عملکرد','ChartNoAxesCombined']]},{label:'مدیریت و پیکربندی',items:[['centers','مراکز توزیع','MapPin'],['drivers','رانندگان','Users'],['chargers','شارژرها','PlugZap'],['shifts','شیفت‌ها','CalendarClock'],['checks','کنترل پیش از شیفت','ClipboardCheck'],['daily_logs','کارکرد روزانه','NotebookPen'],['gates','آمادگی پایلوت','ShieldCheck'],['settings','تنظیمات','Settings'],['presentation','ارائه راهبردی','Presentation']]}]
const validPages=new Set(navigation.flatMap(g=>g.items.map(i=>i[0])))
function initialPage(){const value=window.location.hash.slice(1);return validPages.has(value)?value:'dashboard'}

export default function App(){
  const [user,setUser]=useState<User|null>(null);const [data,setData]=useState<Bootstrap|null>(null);const [booting,setBooting]=useState(true);const [loadError,setLoadError]=useState('');const [page,setPage]=useState(initialPage);const [center,setCenter]=useState('');const [query,setQuery]=useState('');const [mobileMenu,setMobileMenu]=useState(false);const [refreshing,setRefreshing]=useState(false);const [toast,setToast]=useState<{message:string;error:boolean;id:number}|null>(null);const [createNext,setCreateNext]=useState(false)
  const notify=useCallback((message:string,error=false)=>setToast({message,error,id:Date.now()}),[])
  const reload=useCallback(async()=>{const result=await api<Bootstrap>('/bootstrap');setData(result);setLoadError('')},[])
  const navigate=useCallback((next:string)=>{window.location.hash=next;setPage(next);setQuery('');setMobileMenu(false);window.scrollTo({top:0})},[])
  const afterLogin=async(value:{user:User;csrf:string})=>{setUser(value.user);setCsrf(value.csrf);await reload()}
  const initialize=useCallback(async()=>{setBooting(true);setLoadError('');try{const result=await api<{user:User;csrf:string}>('/auth/me');setUser(result.user);setCsrf(result.csrf);await reload()}catch(e){if((e as Error).message!=='لطفاً وارد حساب کاربری شوید.')setLoadError((e as Error).message)}finally{setBooting(false)}},[reload])
  useEffect(()=>{void initialize();const expired=()=>{setUser(null);setData(null);setCsrf('')};const hash=()=>{setPage(initialPage());setQuery('');setMobileMenu(false)};window.addEventListener('session-expired',expired);window.addEventListener('hashchange',hash);return()=>{window.removeEventListener('session-expired',expired);window.removeEventListener('hashchange',hash)}},[initialize])
  useEffect(()=>{if(!toast)return;const id=setTimeout(()=>setToast(null),5500);return()=>clearTimeout(id)},[toast])
  useEffect(()=>{if(data&&center&&!data.records.centers.some(c=>c.id===center))setCenter('')},[data,center])
  const onCreateOpened=useCallback(()=>setCreateNext(false),[])
  const create=(kind:string)=>{navigate(kind);setCreateNext(true)}
  const refresh=async()=>{setRefreshing(true);try{await reload();notify('اطلاعات به‌روز شد.')}catch(e){notify((e as Error).message,true)}finally{setRefreshing(false)}}
  const logout=async()=>{try{await api('/auth/logout','POST');setCsrf('');setUser(null);setData(null);setQuery('');setCenter('');navigate('dashboard')}catch(e){notify((e as Error).message,true)}}
  if(booting)return <div className="loading-screen"><Logo dark/><Icon name="LoaderCircle" size={26} className="spin"/><p>در حال اتصال به سامانه…</p></div>
  if(!user)return <Login onLogin={afterLogin} loadError={loadError}/>
  if(!data)return <div className="loading-screen"><ErrorBox message={loadError||'اطلاعات بارگذاری نشد.'}/><button className="button primary" onClick={()=>void initialize()}>تلاش مجدد</button><button className="button" onClick={logout}>خروج</button></div>
  const title=data.catalog[page]?.label||{dashboard:'داشبورد عملیات',reports:'گزارش‌های عملکرد',settings:'تنظیمات سامانه',presentation:'ارائه راهبردی مپنا'}[page]||'داشبورد'
  const openIncidents=data.records.incidents.filter(i=>!['closed','resolved'].includes(String(i.status))).length
  const isEmpty=!Object.values(data.records).some(r=>r.length)
  return <div className="app-shell">
    {mobileMenu&&<button className="sidebar-scrim" aria-label="بستن فهرست" onClick={()=>setMobileMenu(false)}/>}
    <aside className={'sidebar '+(mobileMenu?'is-open':'')}><div className="sidebar-brand"><Logo/></div><div className="workspace-label"><span className="workspace-avatar">م</span><div><strong>{String(data.settings.organization)}</strong><small>فضای کاری ناوگان</small></div><Icon name="ChevronLeft" size={15}/></div><nav aria-label="منوی اصلی">{navigation.map(group=><div className="nav-group" key={group.label}><div className="nav-label">{group.label}</div>{group.items.map(([id,name,icon])=><button key={id} className={'nav-item '+(page===id?'active':'')} onClick={()=>navigate(id)} aria-current={page===id?'page':undefined}><Icon name={icon} size={19}/><span>{name}</span>{id==='incidents'&&openIncidents>0&&<b>{fa(openIncidents)}</b>}{id==='dashboard'&&page===id&&<i/>}</button>)}</div>)}</nav><div className="sidebar-bottom"><div className="local-status"><i/>سامانه ناوگان<span>v1.1</span></div><button className="nav-item logout" onClick={logout}><Icon name="LogOut" size={18}/><span>خروج از حساب</span></button></div></aside>
    <div className="main-shell"><header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-toggle" aria-label="باز کردن فهرست" onClick={()=>setMobileMenu(true)}><Icon name="Menu"/></button><span>فضای کاری</span><Icon name="ChevronLeft" size={14}/><b>{title}</b></div><div className="topbar-actions"><span className="today"><Icon name="CalendarClock" size={16}/>{date(new Date().toISOString())}</span><button className="notification-button icon-button" aria-label="نمایش هشدارها" onClick={()=>navigate('incidents')}><Icon name="Bell" size={20}/>{openIncidents>0&&<i/>}</button><div className="topbar-divider"/><button className="profile-button" onClick={()=>navigate('settings')}><span className="avatar">{user.name.slice(0,1)}</span><span><strong>{user.name}</strong><small>{data.roles[user.role]}</small></span><Icon name="ChevronLeft" size={15}/></button></div></header>
    <main className={page==='presentation'?'presentation-workspace':undefined}><div className="workspace-toolbar"><div className="center-control"><Icon name="MapPin" size={17}/><select aria-label="انتخاب مرکز توزیع" value={center} onChange={e=>setCenter(e.target.value)}><option value="">همه مراکز توزیع</option>{data.records.centers.map(c=><option key={c.id} value={c.id}>{String(c.name)}</option>)}</select></div><div className="toolbar-end"><span className="sync-label"><i/>{data.demo_count>0?'داده‌های نمایشی':'اطلاعات ثبت‌شده'}</span><button className="icon-button" title="به‌روزرسانی اطلاعات" aria-label="به‌روزرسانی اطلاعات" disabled={refreshing} onClick={refresh}><Icon name="RefreshCw" size={17} className={refreshing?'spin':''}/></button></div></div>
      {data.demo_count>0&&<div className="demo-banner"><Icon name="CircleHelp" size={16}/><span>حالت نمایشی · این اطلاعات ساختگی است و آمار واقعی مپنا نیست.</span>{user.role==='admin'&&<button onClick={()=>navigate('settings')}>مدیریت داده‌ها <Icon name="ChevronLeft" size={14}/></button>}</div>}
      {isEmpty&&user.role==='admin'&&<div className="onboarding-banner"><div><Icon name="Leaf" size={25}/><div><b>به مرکز مدیریت ناوگان خوش آمدید</b><p>از ثبت مرکز توزیع و ناوگان شروع کنید یا امکانات را با داده‌های نمایشی ببینید.</p></div></div><div className="action-row"><button className="button primary" onClick={()=>create('centers')}>ثبت اولین مرکز</button><button className="button" disabled={refreshing} onClick={async()=>{setRefreshing(true);try{await api('/demo/load','POST');await reload();notify('داده‌های نمایشی بارگذاری شد.')}catch(e){notify((e as Error).message,true)}finally{setRefreshing(false)}}}>مشاهده داده نمایشی</button></div></div>}
      {page!=='dashboard'&&<div className="page-heading"><div><span className="eyebrow">مرکز مدیریت ناوگان</span><h1>{title}</h1><p>{data.catalog[page]?.description||{reports:'تصمیم‌گیری بر پایه داده‌های عملیات',settings:'مدیریت دسترسی‌ها، شیفت‌ها و سیاست‌های عملیاتی',presentation:'مرور فایل ارائه و مسیر توسعه ناوگان'}[page]}</p></div>{data.catalog[page]&&<div className="input-icon global-search"><Icon name="Search" size={18}/><input placeholder="جستجوی سریع در این بخش…" aria-label="جستجوی سریع" value={query} onChange={e=>setQuery(e.target.value)}/></div>}</div>}
      {['vehicles','fleets','batteries','charges'].includes(page)&&<FleetBanner kind={page} onExplore={()=>navigate('presentation')}/>}
      <Suspense fallback={<div className="module-loading" role="status"><Icon name="LoaderCircle" className="spin"/><span>در حال آماده‌سازی صفحه…</span></div>}>{page==='dashboard'?<Dashboard data={data} center={center} navigate={navigate} create={create}/>:page==='reports'?<Reports data={data} center={center}/>:page==='settings'?<Settings data={data} user={user} reload={reload} notify={notify} navigate={navigate}/>:page==='presentation'?<Presentation/>:<Records key={page} kind={page} data={data} user={user} reload={reload} notify={notify} query={query} center={center} openCreate={createNext} onCreateOpened={onCreateOpened}/>}</Suspense>
      <footer className="page-footer"><span>مپنا <i/> سامانه مدیریت یکپارچه ناوگان</span><span>آخرین دریافت: {date(data.server_time,true)}</span></footer>
    </main></div>{toast&&<div className={'toast '+(toast.error?'error':'')} role={toast.error?'alert':'status'}><Icon name={toast.error?'TriangleAlert':'CircleCheck'} size={20}/><span>{toast.message}</span><button className="icon-button" aria-label="بستن پیام" onClick={()=>setToast(null)}><Icon name="X" size={16}/></button></div>}
  </div>
}
