import { useEffect, useRef } from 'react'
import type { ReactNode } from 'react'
import { LayoutDashboard, Truck, Bike, Battery, Zap, Flag, TriangleAlert, Headset, ChartNoAxesCombined, Settings, Users, MapPin, PlugZap, CalendarClock, ClipboardCheck, NotebookPen, ShieldCheck, Search, Plus, Download, Upload, RefreshCw, X, ChevronLeft, ChevronRight, ArrowUpLeft, LogOut, Bell, Eye, EyeOff, Pencil, Trash2, Check, CheckCheck, Clock3, CircleHelp, Database, LockKeyhole, ArrowDownToLine, Menu, Leaf, ArrowUpRight, SlidersHorizontal, FileText, KeyRound, CircleCheck, CircleX, Activity, Presentation, Ellipsis, ArrowLeft, LoaderCircle } from 'lucide-react'
const icons = { LayoutDashboard, Truck, Bike, Battery, Zap, Flag, TriangleAlert, Headset, ChartNoAxesCombined, Settings, Users, MapPin, PlugZap, CalendarClock, ClipboardCheck, NotebookPen, ShieldCheck, Search, Plus, Download, Upload, RefreshCw, X, ChevronLeft, ChevronRight, ArrowUpLeft, LogOut, Bell, Eye, EyeOff, Pencil, Trash2, Check, CheckCheck, Clock3, CircleHelp, Database, LockKeyhole, ArrowDownToLine, Menu, Leaf, ArrowUpRight, SlidersHorizontal, FileText, KeyRound, CircleCheck, CircleX, Activity, Presentation, Ellipsis, ArrowLeft, LoaderCircle }
export function Icon({ name, size = 20, className = '' }: { name: string; size?: number; className?: string }) { const C = icons[name as keyof typeof icons] || FileText; return <C size={size} strokeWidth={1.75} className={className} aria-hidden="true" /> }
export function Logo({ dark = false }: { dark?: boolean }) { return <div className={'brand '+(dark?'dark':'')}><span className="brand-mark"><svg viewBox="0 0 40 40" aria-hidden="true"><path d="M8 30V10l12 12 12-12v20" fill="none" stroke="currentColor" strokeWidth="4.5" strokeLinecap="round" strokeLinejoin="round"/></svg></span><div><b>ماهکس<span> / </span>توسن</b><small>مدیریت هوشمند ناوگان</small></div></div> }
const statusLabels: Record<string,string> = { ready:'آماده سرویس',mission:'در مأموریت',charging:'در حال شارژ',out:'خارج از سرویس',maintenance:'نیازمند سرویس',active:'فعال',inactive:'غیرفعال',healthy:'سالم',inspection:'نیازمند بررسی',critical:'بحرانی',high:'مهم',low:'جزئی',completed:'تکمیل شده',failed:'ناموفق',cancelled:'لغو شده',queued:'در صف',planned:'برنامه‌ریزی شده',delayed:'با تأخیر',open:'باز',acknowledged:'تأیید دریافت',repairing:'در حال تعمیر',waiting:'در انتظار قطعه',resolved:'رفع شده',closed:'بسته شده',progress:'در حال بررسی',answered:'پاسخ داده شده',pending:'در انتظار بررسی',passed:'تأیید شده',approved:'تأیید شده',conditional:'مشروط',rejected:'رد شده',fault:'خراب',electric:'برقی',gasoline:'بنزینی' }
export function Status({ value, label }: { value: unknown; label?: string }) { const v=String(value||'');const color=['ready','healthy','active','completed','resolved','closed','passed','approved','answered'].includes(v)?'green':['critical','out','failed','rejected','fault'].includes(v)?'red':['charging','queued','maintenance','inspection','high','waiting','delayed','conditional'].includes(v)?'amber':['mission','progress','repairing','electric','acknowledged'].includes(v)?'blue':'gray';return <span className={'badge '+color}><i/>{label||statusLabels[v]||v||'—'}</span> }
export function Dialog({ title, subtitle, children, onClose, wide=false }: {title:string;subtitle?:string;children:ReactNode;onClose:()=>void;wide?:boolean}) {
  const ref=useRef<HTMLDialogElement>(null)
  useEffect(()=>{ const el=ref.current;el?.showModal();const handler=(e:Event)=>{e.preventDefault();onClose()};el?.addEventListener('cancel',handler);return()=>{el?.removeEventListener('cancel',handler);el?.close()} },[onClose])
  return <dialog ref={ref} className={'modal '+(wide?'wide':'')} aria-label={title}><div className="modal-head"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div><button className="icon-button" onClick={onClose} aria-label="بستن"><Icon name="X"/></button></div>{children}</dialog>
}
export function Empty({ title='هنوز اطلاعاتی ثبت نشده', text='با ثبت اولین رکورد، اطلاعات این بخش نمایش داده می‌شود.', action }: {title?:string;text?:string;action?:ReactNode}) {return <div className="empty"><span><Icon name="Database" size={30}/></span><h3>{title}</h3><p>{text}</p>{action}</div>}
export function ErrorBox({ message }: {message:string}) {return message?<div className="error-box" role="alert"><Icon name="TriangleAlert" size={18}/><span>{message}</span></div>:null}
export function CardHead({title,subtitle,action}:{title:string;subtitle?:string;action?:ReactNode}){return <div className="card-head"><div><h3>{title}</h3>{subtitle&&<p>{subtitle}</p>}</div>{action}</div>}
export function Stat({label,value,unit,icon,tone='green',note}:{label:string;value:ReactNode;unit?:string;icon:string;tone?:string;note?:ReactNode}){return <article className="stat-card"><div className="stat-top"><span>{label}</span><span className={'stat-icon '+tone}><Icon name={icon}/></span></div><div className="stat-value">{value}<small>{unit}</small></div>{note&&<div className="stat-note">{note}</div>}</article>}
