import { useState } from 'react'
import { Bar, BarChart, CartesianGrid, Cell, ComposedChart, Line, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import type { Bootstrap, Row } from './types'
import { CardHead, Empty, Icon, Stat, Status } from './components'
import { centerOf, date, fa, mean, minutes, sla, sum, dayKey } from './utils'
import FleetBanner from './FleetBanner'

const colors=['#119da4','#548bf1','#f4b34c','#ed7779','#9cabb7']
const vehicleStatuses=[['ready','آماده سرویس'],['mission','در مأموریت'],['charging','در حال شارژ'],['out','خارج از سرویس'],['maintenance','نیازمند سرویس']]
const n=(v: unknown)=>fa(Number(v))
const tipStyle={borderRadius:12,border:'1px solid #e3e8ea',fontFamily:'Vazirmatn',fontSize:12,direction:'rtl' as const}
function scoped(data:Bootstrap,center:string){return Object.fromEntries(Object.entries(data.records).map(([kind,rows])=>[kind,center?rows.filter(r=>centerOf(kind,r,data)===center):rows])) as Record<string,Row[]>}
function byPeriod(rows:Row[],key:string,days:number){const cutoff=new Date(Date.now()-(days-1)*86400000).toLocaleDateString('en-CA',{timeZone:'Asia/Tehran'});return rows.filter(r=>dayKey(r[key])>=cutoff&&dayKey(r[key])<=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Tehran'}))}
export function Metrics(data:Bootstrap,center:string,days:number){
  const r=scoped(data,center);const logs=byPeriod(r.daily_logs,'date',days);const missions=byPeriod(r.missions,'started_at',days);const charges=byPeriod(r.charges,'started_at',days);const incidents=byPeriod(r.incidents,'reported_at',days);const tickets=byPeriod(r.tickets,'reported_at',days)
  const planned=sum(logs,'planned_minutes');const available=sum(logs,'available_minutes');const finished=missions.filter(m=>['completed','failed'].includes(String(m.status)));const restored=incidents.filter(i=>i.restored_at);const answered=tickets.filter(t=>t.responded_at)
  const samples=tickets.filter(t=>t.responded_at||!sla(t,data).met)
  return {r,logs,missions,charges,incidents,tickets,planned,available,uptime:planned?available/planned*100:null,downtime:planned?100-available/planned*100:null,success:finished.length?finished.filter(m=>m.status==='completed').length/finished.length*100:null,mttr:restored.length?restored.reduce((s,r)=>s+minutes(r.reported_at,r.restored_at),0)/restored.length:null,response:answered.length?answered.reduce((s,r)=>s+minutes(r.reported_at,r.responded_at),0)/answered.length:null,slaRate:samples.length?samples.filter(t=>sla(t,data).met).length/samples.length*100:null}
}
export function TrendChart({data,center,days=7}:{data:Bootstrap;center:string;days?:number}){
  const m=Metrics(data,center,days)
  const points=Array.from({length:Math.min(days,30)},(_,i)=>{const d=new Date(Date.now()-(Math.min(days,30)-1-i)*86400000);const iso=d.toLocaleDateString('en-CA',{timeZone:'Asia/Tehran'});return {day:new Intl.DateTimeFormat('fa-IR',{day:'numeric',month:'short'}).format(d),missions:m.missions.filter(r=>dayKey(r.started_at)===iso).length,energy:sum(m.charges.filter(r=>dayKey(r.started_at)===iso),'energy_kwh')}})
  return <div className="chart-box" dir="ltr"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={points} margin={{top:12,right:2,left:-24,bottom:0}}><CartesianGrid stroke="#edf0f1" vertical={false}/><XAxis dataKey="day" tick={{fontSize:10,fill:'#8c9499'}} axisLine={false} tickLine={false} minTickGap={8}/><YAxis tickFormatter={n} tick={{fontSize:11,fill:'#8c9499'}} axisLine={false} tickLine={false} allowDecimals={false}/><YAxis yAxisId="energy" orientation="right" tickFormatter={n} tick={{fontSize:11,fill:'#8c9499'}} axisLine={false} tickLine={false} width={30}/><Tooltip contentStyle={tipStyle} formatter={(v,name)=>[fa(Number(v)),name==='missions'?'تعداد مأموریت':'انرژی (kWh)']}/><Bar isAnimationActive={false} dataKey="missions" fill="#79aab7" radius={[5,5,0,0]} maxBarSize={26}/><Line isAnimationActive={false} yAxisId="energy" type="monotone" dataKey="energy" stroke="#377cde" strokeWidth={2.5} dot={{r:3,fill:'#fff',strokeWidth:2}}/></ComposedChart></ResponsiveContainer></div>
}
export function Dashboard({data,center,navigate,create}:{data:Bootstrap;center:string;navigate:(page:string)=>void;create:(kind:string)=>void}){
  const [days,setDays]=useState(7);const m=Metrics(data,center,days);const r=m.r;const vehicles=r.vehicles
  const statusData=vehicleStatuses.map(([value,name],i)=>({name,value:vehicles.filter(v=>v.effective_status===value).length,color:colors[i]})).filter(s=>s.value>0)
  const hist=Array.from({length:5},(_,i)=>({name:`${i*20}–${(i+1)*20}٪`,value:r.batteries.filter(b=>typeof b.soc==='number'&&b.soc>=i*20&&(i===4?b.soc<=100:b.soc<(i+1)*20)).length,color:['#ed8888','#edb56c','#d8c886','#80a2b9','#25768d'][i]}))
  const alerts=[...r.incidents.filter(i=>!['closed','resolved'].includes(String(i.status))).map(i=>({id:i.id,title:String(i.title),code:r.vehicles.find(v=>v.id===i.vehicle_id)?.code||'',text:String(i.owner),severity:String(i.severity),page:'incidents'})),...r.batteries.filter(b=>typeof b.soc==='number'&&b.soc<Number(data.settings.low_soc)).map(b=>({id:b.id,title:'سطح شارژ باتری پایین است',code:b.code,text:`شارژ فعلی: ${fa(Number(b.soc))}٪`,severity:'high',page:'batteries'})),...r.batteries.filter(b=>typeof b.temperature==='number'&&b.temperature>=Number(data.settings.high_temperature)).map(b=>({id:b.id,title:'دمای باتری بالاست',code:b.code,text:`دمای ثبت‌شده: ${fa(Number(b.temperature))}°C`,severity:'critical',page:'batteries'}))]
  const electric=vehicles.filter(v=>v.type==='electric').length
  return <>
    <div className="dashboard-intro"><div><span className="eyebrow">نمای کلی عملیات</span><h1>همهٔ ناوگان، در یک نگاه<span className="heading-dot">.</span></h1><p>وضعیت آمادگی، مأموریت‌ها و انرژی را یکپارچه مدیریت کنید.</p></div><div className="action-row"><select aria-label="بازه گزارش داشبورد" value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>۷ روز گذشته</option><option value={14}>۱۴ روز گذشته</option><option value={30}>۳۰ روز گذشته</option></select>{data.permissions.includes('vehicles')&&<button className="button primary" onClick={()=>create('vehicles')}><Icon name="Plus" size={18}/>ثبت موتورسیکلت</button>}</div></div>
    <FleetBanner onExplore={()=>navigate('presentation')}/>
    <div className="stats-grid dashboard-stats"><Stat label="کل موتورسیکلت‌ها" value={fa(vehicles.length)} unit="دستگاه" icon="Bike" note={<><span className="tiny-dot green"/>{fa(electric)} برقی <span className="stat-divider">/</span> {fa(vehicles.length-electric)} بنزینی</>}/><Stat label="آمادهٔ سرویس" value={fa(vehicles.filter(v=>v.effective_status==='ready').length)} unit="دستگاه" icon="CircleCheck" note="واجد شرایط ثبت‌شدهٔ تخصیص"/><Stat label="در حال مأموریت" value={fa(vehicles.filter(v=>v.effective_status==='mission').length)} unit="دستگاه" icon="Flag" tone="blue" note={<><span className="tiny-dot blue"/>مأموریت‌های فعال ناوگان</>}/><Stat label="نیازمند رسیدگی" value={fa(vehicles.filter(v=>['maintenance','out'].includes(String(v.effective_status))).length)} unit="دستگاه" icon="TriangleAlert" tone="amber" note={<button className="text-button amber" onClick={()=>navigate('incidents')}>بررسی رخدادها <Icon name="ArrowUpLeft" size={14}/></button>}/></div>
    <div className="metric-strip">{[['آماده‌به‌کاری زمانی',fa(m.uptime),'٪','Activity'],['میانگین شارژ باتری',fa(mean(r.batteries,'soc')),'٪','Battery'],['میانگین بازگشت به سرویس',fa(m.mttr),'دقیقه','Clock3'],['انرژی شارژ ثبت‌شده',fa(sum(m.charges,'energy_kwh')),'kWh','Leaf']].map(([title,value,unit,icon])=><div key={title}><span className="metric-icon"><Icon name={icon} size={20}/></span><div><small>{title}</small><b>{value}<em>{unit}</em></b></div></div>)}</div>
    <div className="dashboard-charts"><section className="card"><CardHead title="ترکیب وضعیت ناوگان" subtitle="وضعیت فعلی دستگاه‌ها" action={<Icon name="Ellipsis" size={19}/>}/>{vehicles.length?<><div className="donut"><ResponsiveContainer width="100%" height={166}><PieChart><Pie isAnimationActive={false} data={statusData} dataKey="value" innerRadius={55} outerRadius={73} paddingAngle={4} stroke="none" startAngle={90} endAngle={-270}>{statusData.map(s=><Cell key={s.name} fill={s.color}/>)}</Pie><Tooltip formatter={(v,name)=>[fa(Number(v)),name]} contentStyle={tipStyle}/></PieChart></ResponsiveContainer><div className="donut-label"><strong>{fa(vehicles.length)}</strong><span>موتورسیکلت</span></div></div><div className="chart-legend-list">{statusData.map(s=><div key={s.name}><span><i style={{background:s.color}}/>{s.name}</span><b>{fa(s.value)} <em>{fa(s.value/vehicles.length*100,0)}٪</em></b></div>)}</div></>:<Empty text="ابتدا موتورسیکلت ثبت کنید."/>}</section>
    <section className="card trend-card"><CardHead title="روند مأموریت و مصرف انرژی" subtitle={`${fa(days)} روز گذشته · بر اساس زمان شروع`}/><div className="chart-legend"><span><i style={{background:'#79aab7'}}/>مأموریت <small>محور چپ</small></span><span><i style={{background:'#377cde'}}/>انرژی (kWh) <small>محور راست</small></span></div><TrendChart data={data} center={center} days={days}/><div className="chart-foot"><span>{fa(m.missions.length)} مأموریت ثبت‌شده</span><span className="text-green">{fa(m.success)}٪ موفقیت مأموریت‌های پایان‌یافته</span></div></section>
    <section className="card"><CardHead title="سطح شارژ باتری‌ها" subtitle="توزیع آخرین SOC ثبت‌شده" action={<Icon name="Battery" size={19}/>}/><div className="chart-box histogram" dir="ltr"><ResponsiveContainer width="100%" height="100%"><BarChart data={hist} margin={{top:20,right:5,left:-30,bottom:0}}><CartesianGrid vertical={false} stroke="#edf0f1"/><XAxis dataKey="name" tick={{fontSize:10,fill:'#899095'}} tickLine={false} axisLine={false}/><YAxis allowDecimals={false} tickFormatter={n} tick={{fontSize:10,fill:'#899095'}} tickLine={false} axisLine={false}/><Tooltip formatter={v=>[fa(Number(v)),'تعداد باتری']} contentStyle={tipStyle}/><Bar isAnimationActive={false} dataKey="value" radius={[5,5,0,0]} maxBarSize={35}>{hist.map(h=><Cell key={h.name} fill={h.color}/>)}</Bar></BarChart></ResponsiveContainer></div><div className="chart-foot"><span><i className="tiny-dot amber"/>{fa(r.batteries.filter(b=>b.soc!=null&&Number(b.soc)<Number(data.settings.low_soc)).length)} باتری با شارژ کم</span><button className="text-button" onClick={()=>navigate('batteries')}>مشاهده <Icon name="ChevronLeft" size={13}/></button></div></section></div>
    <div className="dashboard-bottom"><section className="card"><CardHead title="وضعیت موتورسیکلت‌ها" subtitle="آخرین اطلاعات ثبت‌شده در سامانه" action={<button className="text-button" onClick={()=>navigate('vehicles')}>مشاهده همه <Icon name="ArrowUpLeft" size={16}/></button>}/>{vehicles.length?<div className="table-scroll"><table className="dashboard-table"><thead><tr><th>موتورسیکلت</th><th>راننده</th><th>شارژ باتری</th><th>وضعیت</th><th>آخرین تغییر</th></tr></thead><tbody>{vehicles.slice(0,5).map(v=>{const battery=r.batteries.find(b=>b.id===v.battery_id);return <tr key={v.id}><td><div className="vehicle-cell"><span className="vehicle-icon"><Icon name="Bike" size={20}/></span><div><b dir="ltr">{v.code}</b><small>{String(v.model)}</small></div></div></td><td>{String(r.drivers.find(d=>d.id===v.driver_id)?.name||'تخصیص نیافته')}</td><td>{battery?<div className="soc-line"><b>{fa(Number(battery.soc))}٪</b><span className={'mini-meter '+(Number(battery.soc)<25?'low':'')}><i style={{width:Number(battery.soc)+'%'}}/></span></div>:<span className="text-muted">بنزینی</span>}</td><td><Status value={v.effective_status}/></td><td className="text-muted">{date(v.updated_at,true)}</td></tr>})}</tbody></table></div>:<Empty/>}<div className="card-bottom-note"><i className="tiny-dot green"/>داده‌ها پس از ثبت یا به‌روزرسانی نمایش داده می‌شوند.</div></section>
    <section className="card"><CardHead title="هشدارها و پیگیری‌ها" subtitle="موارد نیازمند توجه تیم عملیات" action={<span className="alert-count">{fa(alerts.length)}</span>}/>{alerts.length?<div className="alerts-list">{alerts.slice(0,4).map(a=><button key={a.id} className="alert-row" onClick={()=>navigate(a.page)}><span className={'alert-icon '+(a.severity==='critical'?'red':'amber')}><Icon name="TriangleAlert" size={18}/></span><div><b>{a.title}</b><small><span dir="ltr">{a.code}</span> · {a.text}</small></div><Icon name="ChevronLeft" size={14}/></button>)}</div>:<div className="calm-empty"><Icon name="ShieldCheck" size={32}/><b>هشداری ثبت نشده است</b><small>وضعیت بر اساس داده‌های موجود است.</small></div>}<div className="support-summary"><span><Icon name="Headset" size={18}/>میانگین پاسخ پشتیبانی</span><b>{fa(m.response)} <small>دقیقه</small></b></div><button className="full-link" onClick={()=>navigate('tickets')}>ورود به مرکز پشتیبانی <Icon name="ArrowUpLeft" size={15}/></button></section></div>
  </>
}

export function Reports({data,center}:{data:Bootstrap;center:string}){
  const [days,setDays]=useState(7);const m=Metrics(data,center,days)
  const exportReport=()=>{const rows=[['مرکز','موتورها','آماده‌به‌کاری (%)','مسافت (km)','انرژی شارژ (kWh)','موفقیت مأموریت (%)','هزینه نگهداری (تومان)'],...data.records.centers.filter(c=>!center||c.id===center).map(c=>{const a=Metrics(data,c.id,days);return [String(c.name),a.r.vehicles.length,a.uptime??'',sum(a.logs,'distance_km'),sum(a.charges,'energy_kwh'),a.success??'',sum(a.logs,'maintenance_cost')]})];const content=rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\ufeff',content],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='fleet-performance.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  return <><div className="section-actions"><p>تحلیل داده‌های ثبت‌شده در دوره انتخابی</p><div className="action-row"><select value={days} onChange={e=>setDays(Number(e.target.value))} aria-label="بازه گزارش"><option value={7}>۷ روز گذشته</option><option value={14}>۱۴ روز گذشته</option><option value={30}>۳۰ روز گذشته</option></select><button className="button" onClick={exportReport}><Icon name="Download" size={17}/>خروجی گزارش</button><button className="button" onClick={()=>window.print()}><Icon name="FileText" size={17}/>چاپ گزارش</button></div></div><div className="stats-grid"><Stat label="آماده‌به‌کاری زمانی" value={fa(m.uptime)} unit="درصد" icon="Activity" note={`${fa(sum(m.logs,'available_minutes'))} از ${fa(sum(m.logs,'planned_minutes'))} دقیقه`}/><Stat label="موفقیت مأموریت" value={fa(m.success)} unit="درصد" icon="Flag" tone="blue" note="نسبت موفق به موفق و ناموفق"/><Stat label="پیمایش ثبت‌شده" value={fa(sum(m.logs,'distance_km'))} unit="کیلومتر" icon="Truck" note="مجموع کارکردهای روزانه"/><Stat label="انرژی شارژ" value={fa(sum(m.charges,'energy_kwh'))} unit="kWh" icon="Leaf" note="مجموع انرژی نوبت‌های ثبت‌شده"/></div><div className="reports-grid"><section className="card"><CardHead title="مأموریت و انرژی" subtitle="مقایسه روند دوره انتخابی"/><TrendChart data={data} center={center} days={days}/></section><section className="card"><CardHead title="شاخص‌های خدمت" subtitle="اهداف آزمایشی قابل تغییر در تنظیمات"/><div className="report-measures">{[['توقف زمان برنامه‌ریزی شده',fa(m.downtime)+'٪'],['میانگین بازگشت از خرابی',fa(m.mttr)+' دقیقه'],['میانگین اولین پاسخ',fa(m.response)+' دقیقه'],['پاسخ در هدف SLA',fa(m.slaRate)+'٪'],['هزینه نگهداری',fa(sum(m.logs,'maintenance_cost'))+' تومان'],['مصرف بنزین ثبت‌شده',fa(sum(m.logs,'fuel_liters'))+' لیتر']].map(([name,value])=><div key={name}><span>{name}</span><b>{value}</b></div>)}</div></section></div><section className="card"><CardHead title="عملکرد مراکز توزیع" subtitle={`${fa(days)} روز گذشته`}/><div className="table-scroll"><table><thead><tr><th>مرکز توزیع</th><th>تعداد موتور</th><th>آماده‌به‌کاری</th><th>پیمایش</th><th>انرژی شارژ</th><th>موفقیت مأموریت</th></tr></thead><tbody>{data.records.centers.filter(c=>!center||c.id===center).map(c=>{const a=Metrics(data,c.id,days);return <tr key={c.id}><td>{String(c.name)}</td><td>{fa(a.r.vehicles.length)}</td><td>{fa(a.uptime)}٪</td><td>{fa(sum(a.logs,'distance_km'))} km</td><td>{fa(sum(a.charges,'energy_kwh'))} kWh</td><td>{fa(a.success)}٪</td></tr>})}</tbody></table></div></section><div className="notice"><Icon name="CircleHelp"/><div><b>روش محاسبه</b><p>آماده‌به‌کاری = زمان آماده‌به‌کار ÷ زمان برنامه‌ریزی‌شده در کارکرد روزانه. زمان بازگشت = زمان بازگشت به سرویس منهای وقوع خرابی. داده مفقود با «—» نمایش داده می‌شود. SLA شامل پاسخ‌های ثبت‌شده و درخواست‌های بی‌پاسخِ عبورکرده از مهلت است. هیچ شاخصی داده زنده GPS یا BMS محسوب نمی‌شود.</p></div></div></>
}
