import { useEffect, useMemo, useRef, useState, useCallback } from 'react'
import type { Bootstrap, Field, Notify, Row, User, Value } from './types'
import { api, download } from './api'
import { Icon, Dialog, Empty, ErrorBox, Status, Stat } from './components'
import { centerOf, date, fa, label, localInputNow, mean, norm, sla, sum, epoch } from './utils'
import ModuleCharts from './ModuleCharts'

export function display(field: Field, value: Value | undefined, data: Bootstrap): string {
  if (value==null||value==='') return '—'
  if(field.type==='checkbox')return value?'بله':'خیر'
  if(field.type==='reference') { const r=data.records[field.source!]?.find(r=>r.id===value);return r?`${r.code} · ${label(r)}`:'—' }
  if(field.type==='multi-reference')return (value as string[]).map(id=>label(data.records[field.source!].find(r=>r.id===id))).join('، ')||'—'
  if(field.type==='select')return field.options?.find(o=>o.value===value)?.label||String(value)
  if(field.type==='number')return fa(Number(value))
  if(field.type==='date'||field.type==='datetime-local')return date(value,field.type==='datetime-local')
  return Array.isArray(value)?value.join('، '):String(value)
}
export function Cell({field,row,data}:{field:Field;row:Row;data:Bootstrap}){
  const val=field.key==='status'&&row.effective_status?row.effective_status:row[field.key]
  if(['status','severity','priority','type'].includes(field.key))return <Status value={val} label={row.effective_status?undefined:field.options?.find(o=>o.value===val)?.label}/>
  if(['soc','soh'].includes(field.key)&&typeof val==='number')return <span className="battery-value"><span className={'mini-meter '+(val<25?'low':'')}><i style={{width:val+'%'}}/></span>{fa(val)}٪</span>
  if(field.key==='code')return <b className="record-code" dir="ltr">{String(val)}</b>
  if(field.type==='checkbox')return <span className={val?'text-green':'text-muted'}><Icon name={val?'CircleCheck':'CircleX'} size={18}/></span>
  return <span className="cell-text" title={display(field,val,data)}>{display(field,val,data)}</span>
}
export function RecordEditor({kind,row,data,readonly,onClose,onSaved}:{kind:string;row?:Row;data:Bootstrap;readonly?:boolean;onClose:()=>void;onSaved:()=>Promise<void>}){
  const meta=data.catalog[kind]
  const [values,setValues]=useState<Record<string,Value>>(()=>Object.fromEntries(meta.fields.map(f=>{
    let value=row?.[f.key]??f.default??(f.type==='checkbox'?false:['days','multi-reference'].includes(f.type)?[]:'')
    if(f.key==='code'&&!row){const prefix={vehicles:'M',batteries:'B',missions:'MS',fleets:'F',chargers:'CH',charges:'CS',drivers:'D',incidents:'IN',tickets:'TK'}[kind]||kind.slice(0,3).toUpperCase();const nums=data.records[kind].map(r=>Number(r.code.split('-').at(-1))).filter(Number.isFinite);value=prefix+'-'+String(Math.max(0,...nums)+1).padStart(3,'0')}
    if(!row&&f.required&&f.type==='datetime-local')value=localInputNow()
    if(value&&f.type==='datetime-local'){const ts=epoch(value);if(Number.isFinite(ts))value=new Date(ts+3.5*3600000).toISOString().slice(0,16)}
    return [f.key,value]
  })))
  const [error,setError]=useState('');const [busy,setBusy]=useState(false)
  const set=(key:string,value:Value)=>setValues(v=>({...v,[key]:value}))
  const submit=async(e:React.SubmitEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setError('');try{await api('/records/'+kind+(row?'/'+row.id:''),row?'PUT':'POST',values);await onSaved();onClose()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <Dialog title={(readonly?'جزئیات ':row?'ویرایش ':'ثبت ')+meta.singular} subtitle={readonly&&row?`آخرین تغییر: ${date(row.updated_at,true)}`:'اطلاعات را وارد کنید. فیلدهای ستاره‌دار الزامی هستند.'} onClose={onClose} wide>
    <form onSubmit={submit}><div className="modal-body"><ErrorBox message={error}/>{kind==='vehicles'&&row&&<div className={'notice '+((row.readiness_reasons as string[])?.length?'warm':'success')}><Icon name="ShieldCheck"/><div><b>وضعیت آمادگی</b><p>{(row.readiness_reasons as string[])?.length?(row.readiness_reasons as string[]).join(' · '):'کنترل‌های ثبت‌شده برای تخصیص مأموریت تأیید است.'}</p></div></div>}
      <div className="form-grid">{meta.fields.map(field=>{
        const value=values[field.key]; const id='field-'+field.key
        if(readonly)return <div className={'detail-field '+(field.type==='textarea'?'full':'')} key={field.key}><span>{field.label}</span><strong>{display(field,value,data)}</strong></div>
        return <div className={'form-field '+(['textarea','days','multi-reference'].includes(field.type)?'full':'')+(field.type==='checkbox'?' checkbox-field':'')} key={field.key}>
          {field.type!=='checkbox'&&<label htmlFor={id}>{field.label}{field.required&&<em aria-hidden="true"> *</em>}</label>}
          {field.type==='select'?<select id={id} required={field.required} value={String(value??'')} onChange={e=>set(field.key,e.target.value)}><option value="">انتخاب کنید</option>{field.options?.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>
          :field.type==='reference'?<><select id={id} required={field.required} value={String(value??'')} onChange={e=>set(field.key,e.target.value)}><option value="">انتخاب کنید</option>{data.records[field.source!].map(r=><option key={r.id} value={r.id}>{r.code} · {label(r)}{field.source==='vehicles'&&kind==='missions'&&r.effective_status!=='ready'?' (آماده نیست)':''}</option>)}</select>{!data.records[field.source!].length&&<small className="text-amber">ابتدا در بخش «{data.catalog[field.source!].label}» رکورد ثبت کنید.</small>}</>
          :field.type==='checkbox'?<label className="check-label" htmlFor={id}><input id={id} type="checkbox" checked={!!value} onChange={e=>set(field.key,e.target.checked)}/><span>{field.label}</span></label>
          :field.type==='textarea'?<textarea id={id} rows={3} maxLength={4000} value={String(value??'')} required={field.required} onChange={e=>set(field.key,e.target.value)}/>
          :field.type==='days'||field.type==='multi-reference'?<div className="multi-check">{(field.type==='days'?['شنبه','یکشنبه','دوشنبه','سه‌شنبه','چهارشنبه','پنجشنبه','جمعه'].map(d=>({id:d,label:d})):data.records[field.source!].map(r=>({id:r.id,label:label(r)}))).map(o=><label key={o.id}><input type="checkbox" checked={(value as string[]).includes(o.id)} onChange={e=>set(field.key,e.target.checked?[...(value as string[]),o.id]:(value as string[]).filter(v=>v!==o.id))}/>{o.label}</label>)}</div>
          :<><input id={id} type={field.type} min={field.min} max={field.max} step={field.type==='number'?'any':undefined} dir={['number','date','datetime-local','time'].includes(field.type)||['code','vin','gps_id'].includes(field.key)?'ltr':undefined} value={value==null?'':String(value)} required={field.required} maxLength={4000} onChange={e=>set(field.key,field.type==='number'?(e.target.value===''?null:Number(e.target.value)):e.target.value)}/>{['date','datetime-local'].includes(field.type)&&<small>ورود تاریخ میلادی؛ نمایش در فهرست به شمسی</small>}</>}
        </div>
      })}</div></div><div className="modal-footer">{!readonly&&<button className="button primary" disabled={busy} type="submit"><Icon name={busy?'LoaderCircle':'Check'} className={busy?'spin':''}/>{busy?'در حال ذخیره…':'ذخیره اطلاعات'}</button>}<button type="button" className="button" onClick={onClose}>{readonly?'بستن':'انصراف'}</button></div></form>
  </Dialog>
}

export default function Records({kind,data,user,reload,notify,query='',center='',openCreate=false,onCreateOpened}:{kind:string;data:Bootstrap;user:User;reload:()=>Promise<void>;notify:Notify;query?:string;center?:string;openCreate?:boolean;onCreateOpened:()=>void}){
  const meta=data.catalog[kind];const all=data.records[kind];const canEdit=data.permissions.includes(kind)
  const [search,setSearch]=useState('');const [status,setStatus]=useState('');const [from,setFrom]=useState('');const [to,setTo]=useState('');const [page,setPage]=useState(0);const [editor,setEditor]=useState<{row?:Row;readonly?:boolean}|null>(null);const [deleting,setDeleting]=useState<Row|null>(null);const [busy,setBusy]=useState(false);const [importing,setImporting]=useState(false);const file=useRef<HTMLInputElement>(null)
  const close=useCallback(()=>setEditor(null),[])
  useEffect(()=>{setSearch('');setStatus('');setFrom('');setTo('');setPage(0)},[kind])
  useEffect(()=>{if(openCreate){setEditor({});onCreateOpened()}},[openCreate,onCreateOpened])
  const filtered=useMemo(()=>all.filter(r=>{
    if(center&&centerOf(kind,r,data)!==center)return false
    if(status&&(r.effective_status||r.status)!==status)return false
    const day=String(r.date||r.started_at||r.reported_at||r.checked_at||r.created_at).slice(0,10)
    if(from&&day<from||to&&day>to)return false
    const hay=norm(meta.fields.map(f=>display(f,r[f.key],data)).join(' '))
    return (!search||hay.includes(norm(search)))&&(!query||hay.includes(norm(query)))
  }),[all,center,kind,data,status,from,to,search,query,meta])
  useEffect(()=>setPage(0),[search,status,from,to,query,center])
  const currentPage=Math.min(page,Math.max(0,Math.ceil(filtered.length/10)-1));const visible=filtered.slice(currentPage*10,currentPage*10+10)
  const saved=async()=>{await reload();notify('اطلاعات با موفقیت ذخیره شد.')}
  const remove=async()=>{if(!deleting)return;setBusy(true);try{await api(`/records/${kind}/${deleting.id}`,'DELETE');setDeleting(null);await reload();notify('رکورد حذف شد.')}catch(e){notify((e as Error).message,true)}finally{setBusy(false)}}
  const exportRows=()=>{const fields=meta.fields;const escape=(v:string)=>'"'+v.replaceAll('"','""')+'"';const safe=(v:string)=>/^[\s]*[=+\-@]/.test(v)?"'"+v:v;const body=[fields.map(f=>f.label),...filtered.map(r=>fields.map(f=>display(f,r[f.key],data)))].map(row=>row.map(v=>escape(safe(v))).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\ufeff',body],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=kind+'-report.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notify('خروجی ردیف‌های فیلترشده آماده شد.')}
  const importFile=async(f:File)=>{setImporting(true);try{if(f.size>2000000)throw new Error('حجم فایل باید کمتر از ۲ مگابایت باشد.');const result=await api<{imported:number}>('/import/'+kind,'POST',{content:await f.text()});await reload();notify(`${fa(result.imported)} ردیف وارد شد.`)}catch(e){notify((e as Error).message,true)}finally{setImporting(false);if(file.current)file.current.value=''}}
  const relatedCount=kind==='fleets'?data.records.vehicles.filter(v=>filtered.some(f=>v.fleet_id===f.id)).length:kind==='centers'?data.records.fleets.filter(f=>filtered.some(c=>c.id===f.center_id)).length:null
  const stats=kind==='vehicles'?[['کل موتورسیکلت‌ها',filtered.length,'Bike','green'],['آماده سرویس',filtered.filter(r=>r.effective_status==='ready').length,'CircleCheck','green'],['در مأموریت',filtered.filter(r=>r.effective_status==='mission').length,'Flag','blue'],['نیازمند رسیدگی',filtered.filter(r=>['out','maintenance'].includes(String(r.effective_status))).length,'TriangleAlert','amber']]:kind==='batteries'?[['کل باتری‌ها',filtered.length,'Battery','green'],['میانگین شارژ',mean(filtered,'soc'),'Zap','blue'],['میانگین سلامت',mean(filtered,'soh'),'Activity','green'],['نیازمند بررسی',filtered.filter(r=>r.status!=='healthy').length,'TriangleAlert','amber']]:kind==='charges'?[['کل نوبت‌ها',filtered.length,'PlugZap','green'],['شارژ فعال',filtered.filter(r=>r.status==='charging').length,'Zap','blue'],['انرژی ثبت‌شده',sum(filtered,'energy_kwh'),'Leaf','green'],['در صف',filtered.filter(r=>r.status==='queued').length,'Clock3','amber']]:kind==='missions'?[['کل مأموریت‌ها',filtered.length,'Flag','blue'],['تکمیل شده',filtered.filter(r=>r.status==='completed').length,'CircleCheck','green'],['در حال اجرا',filtered.filter(r=>['active','delayed'].includes(String(r.status))).length,'Activity','blue'],['ناموفق / تأخیر',filtered.filter(r=>['failed','delayed'].includes(String(r.status))).length,'Clock3','amber']]:kind==='tickets'?[['کل درخواست‌ها',filtered.length,'Headset','blue'],['درخواست باز',filtered.filter(r=>r.status!=='closed').length,'FileText','amber'],['پاسخ در هدف SLA',filtered.filter(r=>r.responded_at&&sla(r,data).met).length,'ShieldCheck','green'],['عبور از هدف پاسخ',filtered.filter(r=>!sla(r,data).met).length,'Clock3','red']]:[['تعداد رکوردها',filtered.length,meta.icon,'green'],['فعال / تأیید شده',filtered.filter(r=>['active','ready','passed','approved','healthy','resolved','closed'].includes(String(r.status))).length,'CircleCheck','green'],['نیازمند توجه',filtered.filter(r=>['open','critical','fault','pending','conditional'].includes(String(r.status))).length,'TriangleAlert','amber'],[relatedCount!==null?(kind==='fleets'?'موتورهای مرتبط':'ناوگان‌های مرتبط'):'داده نمایشی',relatedCount??filtered.filter(r=>r.demo).length,relatedCount!==null?'Truck':'FileText','blue']]
  return <><div className="stats-grid">{stats.map((s,i)=><Stat key={i} label={String(s[0])} value={fa(s[1] as number|null)} icon={String(s[2])} tone={String(s[3])} unit={kind==='batteries'&&[1,2].includes(i)?'درصد':kind==='charges'&&i===2?'kWh':undefined} note="بر اساس رکوردهای همین نما"/>)}</div>
    <ModuleCharts kind={kind} rows={filtered} data={data}/>
    {kind==='tickets'&&<div className="notice"><Icon name="CircleHelp"/><p>اهداف SLA آزمایشی و قابل تنظیم هستند. زمان پاسخ از ثبت درخواست تا اولین پاسخ محاسبه می‌شود؛ زمان بازگشت به سرویس در بخش خرابی‌ها ثبت می‌شود.</p></div>}
    {kind==='gates'&&<div className="notice warm"><Icon name="ShieldCheck"/><p>ثبت خرید یا تکمیل فرم به معنای مجوز پایلوت نیست. هر پیش‌شرط باید با شواهد و تصمیم مسئول مربوط تأیید شود.</p></div>}
    <section className="card records-card"><div className="records-header"><div><h3>فهرست {meta.label}</h3><span className="count-pill">{fa(filtered.length)} مورد</span></div><div className="action-row"><button className="button small" onClick={exportRows}><Icon name="Download" size={16}/>خروجی CSV</button>{user.role==='admin'&&<><button className="button small" disabled={importing} onClick={()=>file.current?.click()}><Icon name="Upload" size={16}/>{importing?'در حال ورود…':'ورود CSV'}</button><button className="text-button" onClick={()=>download('/export/'+kind+'?template=true',kind+'-template.csv').catch(e=>notify(e.message,true))}>قالب ورود</button><input ref={file} type="file" accept=".csv,text/csv" hidden onChange={e=>e.target.files?.[0]&&void importFile(e.target.files[0])}/></>}{canEdit&&<button className="button primary small" onClick={()=>setEditor({})}><Icon name="Plus" size={17}/>ثبت {meta.singular}</button>}</div></div>
      <div className="table-toolbar"><div className="input-icon"><Icon name="Search" size={18}/><input aria-label="جستجو در فهرست" placeholder={`جستجو در ${meta.label}…`} value={search} onChange={e=>setSearch(e.target.value)}/></div>{meta.fields.some(f=>f.key==='status')&&<select aria-label="فیلتر وضعیت" value={status} onChange={e=>setStatus(e.target.value)}><option value="">همه وضعیت‌ها</option>{(kind==='vehicles'?[{value:'ready',label:'آماده سرویس'},{value:'mission',label:'در مأموریت'},{value:'charging',label:'در حال شارژ'},{value:'out',label:'خارج از سرویس'},{value:'maintenance',label:'نیازمند سرویس'}]:meta.fields.find(f=>f.key==='status')?.options)?.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>}<label className="date-filter">از <input aria-label="از تاریخ میلادی" type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="date-filter">تا <input aria-label="تا تاریخ میلادی" type="date" value={to} min={from} onChange={e=>setTo(e.target.value)}/></label>{(search||status||from||to)&&<button className="icon-button" aria-label="پاک کردن فیلترها" onClick={()=>{setSearch('');setStatus('');setFrom('');setTo('')}}><Icon name="X" size={17}/></button>}</div>
      {visible.length?<div className="table-scroll"><table><thead><tr>{meta.columns.map(k=><th key={k}>{meta.fields.find(f=>f.key===k)?.label}</th>)}{kind==='tickets'&&<th>هدف پاسخ SLA</th>}<th>عملیات</th></tr></thead><tbody>{visible.map(row=><tr key={row.id}>{meta.columns.map(k=><td key={k}><Cell field={meta.fields.find(f=>f.key===k)!} row={row} data={data}/></td>)}{kind==='tickets'&&<td><Status value={sla(row,data).met?'ready':'critical'} label={sla(row,data).met?'در محدوده هدف':'عبور از هدف'}/></td>}<td><div className="row-actions"><button className="icon-button" aria-label={'مشاهده '+row.code} title="مشاهده جزئیات" onClick={()=>setEditor({row,readonly:true})}><Icon name="Eye" size={17}/></button>{canEdit&&<button className="icon-button" aria-label={'ویرایش '+row.code} title="ویرایش اطلاعات و وضعیت" onClick={()=>setEditor({row})}><Icon name="Pencil" size={16}/></button>}{user.role==='admin'&&<button className="icon-button danger" aria-label={'حذف '+row.code} title="حذف" onClick={()=>setDeleting(row)}><Icon name="Trash2" size={16}/></button>}</div></td></tr>)}</tbody></table></div>:<Empty title={all.length?'رکوردی با این فیلترها پیدا نشد':'اولین '+meta.singular+' را ثبت کنید'} action={canEdit&&!all.length?<button className="button primary" onClick={()=>setEditor({})}><Icon name="Plus" size={18}/>ثبت {meta.singular}</button>:undefined}/>}
      <div className="table-footer"><span>{filtered.length?`نمایش ${fa(currentPage*10+1)} تا ${fa(Math.min((currentPage+1)*10,filtered.length))} از ${fa(filtered.length)} مورد`:'۰ مورد'}</span><div><button className="icon-button" disabled={currentPage===0} onClick={()=>setPage(currentPage-1)} aria-label="صفحه قبل"><Icon name="ChevronRight" size={18}/></button><span className="page-number">{fa(currentPage+1)}</span><button className="icon-button" disabled={(currentPage+1)*10>=filtered.length} onClick={()=>setPage(currentPage+1)} aria-label="صفحه بعد"><Icon name="ChevronLeft" size={18}/></button></div></div>
    </section>
    {editor&&<RecordEditor key={kind+(editor.row?.id||'new')} kind={kind} row={editor.row} data={data} readonly={editor.readonly} onClose={close} onSaved={saved}/>}
    {deleting&&<Dialog title="حذف رکورد" onClose={()=>setDeleting(null)}><div className="modal-body"><p>رکورد <b dir="ltr">{deleting.code}</b> حذف شود؟ سوابق مرتبط مانع حذف خواهند شد.</p></div><div className="modal-footer"><button className="button destructive" disabled={busy} onClick={remove}>حذف رکورد</button><button className="button" onClick={()=>setDeleting(null)}>انصراف</button></div></Dialog>}
  </>
}
