import { useCallback, useEffect, useState } from 'react'
import type { Bootstrap, Notify, User, Value } from './types'
import { api, download } from './api'
import { CardHead, Dialog, Empty, ErrorBox, Icon, Status } from './components'
import { date, fa } from './utils'

const settingsLabels:Record<string,string>={organization:'نام سازمان',low_soc:'هشدار شارژ پایین (%)',min_dispatch_soc:'حداقل شارژ تخصیص مأموریت (%)',high_temperature:'هشدار دمای باتری (°C)',stale_hours:'حداکثر عمر داده باتری (ساعت)',sla_critical_minutes:'پاسخ بحرانی (دقیقه)',sla_high_minutes:'پاسخ مهم (دقیقه)',sla_low_minutes:'پاسخ جزئی (دقیقه)',sla_restore_hours:'هدف بازگشت بحرانی (ساعت)',target_uptime:'هدف آماده‌به‌کاری (%)',target_success:'هدف موفقیت مأموریت (%)'}
export default function Settings({data,user,reload,notify,navigate}:{data:Bootstrap;user:User;reload:()=>Promise<void>;notify:Notify;navigate:(p:string)=>void}){
  const isAdmin=user.role==='admin';const [tab,setTab]=useState(isAdmin?'general':'password');const [values,setValues]=useState({...data.settings});const [busy,setBusy]=useState(false);const [users,setUsers]=useState<User[]>([]);const [audit,setAudit]=useState<Record<string,string>[]>([]);const [userForm,setUserForm]=useState<User|true|null>(null);const [confirm,setConfirm]=useState(false);const [error,setError]=useState('')
  const closeUser=useCallback(()=>setUserForm(null),[])
  const fetchUsers=useCallback(async()=>{try{setUsers(await api<User[]>('/users'))}catch(e){notify((e as Error).message,true)}},[notify])
  useEffect(()=>{if(tab==='users')void fetchUsers();if(tab==='audit')api<Record<string,string>[]>('/audit').then(setAudit).catch(e=>notify(e.message,true))},[tab,fetchUsers,notify])
  const run=async(fn:()=>Promise<unknown>,message:string)=>{setBusy(true);setError('');try{await fn();await reload();notify(message)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <><div className="tabs">{[...(isAdmin?[['general','تنظیمات عمومی','Settings'],['users','کاربران و نقش‌ها','Users'],['data','داده و پشتیبان','Database'],['audit','تاریخچه تغییرات','NotebookPen']]:[]),['password','رمز عبور','LockKeyhole']].map(([id,title,icon])=><button className={tab===id?'active':''} key={id} onClick={()=>{setTab(id);setError('')}}><Icon name={icon} size={17}/>{title}</button>)}</div><ErrorBox message={error}/>
    {tab==='general'&&<div className="settings-layout"><section className="card"><CardHead title="هویت سامانه و آستانه‌ها" subtitle="تغییرات روی کنترل آمادگی و هشدارها اعمال می‌شوند."/><form onSubmit={e=>{e.preventDefault();void run(()=>api('/settings','PUT',Object.fromEntries(Object.keys(settingsLabels).map(k=>[k,values[k]]))),'تنظیمات ذخیره شد.')}}><div className="form-grid padded">{Object.entries(settingsLabels).map(([k,v])=><div className="form-field" key={k}><label htmlFor={'setting-'+k}>{v}</label><input id={'setting-'+k} type={k==='organization'?'text':'number'} min={0.1} max={['low_soc','min_dispatch_soc','target_uptime','target_success'].includes(k)?100:100000} step="any" required value={String(values[k]??'')} onChange={e=>setValues({...values,[k]:k==='organization'?e.target.value:Number(e.target.value)})}/></div>)}</div><div className="modal-footer"><button className="button primary" disabled={busy}><Icon name="Check" size={18}/>ذخیره تنظیمات</button></div></form></section><div className="settings-side"><section className="card"><CardHead title="مدیریت عملیات"/><div className="settings-links">{[['shifts','تعریف شیفت‌ها','CalendarClock'],['centers','مراکز توزیع','MapPin'],['drivers','رانندگان و آموزش','Users'],['checks','کنترل پیش از شیفت','ClipboardCheck'],['gates','دروازه‌های آمادگی پایلوت','ShieldCheck']].map(([page,title,icon])=><button key={page} onClick={()=>navigate(page)}><Icon name={icon} size={18}/>{title}<Icon name="ChevronLeft" size={16}/></button>)}</div></section><div className="notice warm"><Icon name="CircleHelp"/><p>مقادیر SLA اهداف اولیه پایلوت هستند و به‌تنهایی تعهد قراردادی محسوب نمی‌شوند. آن‌ها را بر اساس توافق و داده واقعی تنظیم کنید.</p></div></div></div>}
    {tab==='users'&&<section className="card"><CardHead title="کاربران و سطح دسترسی" subtitle="دسترسی هر کاربر بر اساس نقش او کنترل می‌شود." action={<button className="button primary small" onClick={()=>setUserForm(true)}><Icon name="Plus" size={17}/>افزودن کاربر</button>}/><div className="table-scroll"><table><thead><tr><th>نام</th><th>نام کاربری</th><th>نقش</th><th>وضعیت</th><th>عملیات</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.name}</td><td dir="ltr">{u.username}</td><td>{data.roles[u.role]}</td><td><Status value={u.active?'active':'inactive'}/></td><td><button className="button small" onClick={()=>setUserForm(u)}><Icon name="Pencil" size={15}/>ویرایش</button></td></tr>)}</tbody></table></div><div className="permission-grid">{Object.entries(data.roles).map(([role,title])=><div key={role}><Icon name={role==='admin'?'ShieldCheck':'Users'} size={20}/><b>{title}</b><small>{{admin:'تمام بخش‌ها، مدیریت کاربران و پشتیبان',operator:'مأموریت، رخداد، پشتیبانی، کنترل و کارکرد',technician:'باتری، خرابی و پشتیبانی',charging:'باتری و نوبت شارژ',viewer:'مشاهده اطلاعات و دریافت گزارش'}[role]}</small></div>)}</div></section>}
    {tab==='data'&&<div className="settings-layout"><div className="stack"><section className="card"><CardHead title="نسخه پشتیبان پایگاه داده" subtitle="نسخه سازگار SQLite شامل اطلاعات، کاربران و سوابق"/><div className="padded"><div className="data-feature"><span className="feature-icon"><Icon name="Database" size={30}/></span><div><h3>اطلاعات ناوگان همراه شما</h3><p>فایل پشتیبان را برای نگهداری و انتقال اطلاعات دریافت کنید. روش بازیابی در راهنمای پروژه آمده است.</p></div></div><button className="button primary" disabled={busy} onClick={()=>run(()=>download('/backup','mahax-fleet-backup.sqlite3'),'فایل پشتیبان دریافت شد.')}><Icon name="Download" size={18}/>دریافت نسخه پشتیبان</button></div></section><section className="card"><CardHead title="داده نمایشی" subtitle="رکوردهای ساختگی برای بررسی و ارائه امکانات"/><div className="padded"><p>{data.demo_count?`${fa(data.demo_count)} رکورد نمایشی در سامانه وجود دارد. این داده‌ها آمار واقعی ماهکس نیستند.`:'پایگاه داده آماده ثبت اطلاعات واقعی است. برای مشاهده نمونه، پایگاه باید خالی باشد.'}</p>{data.demo_count?<button className="button danger-outline" disabled={busy} onClick={()=>setConfirm(true)}><Icon name="Trash2" size={17}/>پاک‌سازی داده‌های نمایشی</button>:<button className="button" disabled={busy||Object.values(data.records).some(rows=>rows.length>0)} onClick={()=>run(()=>api('/demo/load','POST'),'داده‌های نمایشی بارگذاری شدند.')}><Icon name="Plus" size={18}/>بارگذاری داده نمایشی</button>}</div></section></div><section className="card"><CardHead title="ورود و خروج اطلاعات"/><div className="padded"><p>هر بخش دارای خروجی CSV، قالب ورود و ورود گروهی است. فایل‌ها با Excel سازگارند.</p><ol className="instruction-list"><li>قالب CSV همان بخش را دریافت کنید.</li><li>نام ستون‌های انگلیسی را حفظ کنید.</li><li>برای ارتباط‌ها، شناسهٔ رکورد مانند M-001 را وارد کنید.</li><li>مقادیر وضعیت باید کلید انگلیسی باشند؛ توضیح کلیدها در راهنما آمده است.</li><li>ورود فایل به‌صورت یک تراکنش است؛ خطای هر ردیف کل فایل را بازمی‌گرداند.</li></ol><p className="text-muted">خروجی فارسی برای گزارش است. خروجی قابل ورود مجدد از دکمه زیر دریافت می‌شود.</p><select aria-label="انتخاب بخش برای خروجی قابل ورود" defaultValue="" onChange={e=>{if(e.target.value)void download('/export/'+e.target.value,e.target.value+'.csv').catch(e=>notify(e.message,true));e.target.value=''}}><option value="">دریافت خروجی قابل ورود…</option>{Object.entries(data.catalog).map(([k,v])=><option key={k} value={k}>{v.label}</option>)}</select></div></section></div>}
    {tab==='audit'&&<section className="card"><CardHead title="تاریخچه فعالیت‌ها" subtitle="۲۵۰ رویداد اخیر؛ قابل تغییر از رابط کاربری نیست"/>{audit.length?<div className="table-scroll"><table><thead><tr><th>زمان</th><th>کاربر</th><th>عملیات</th><th>بخش</th><th>جزئیات</th></tr></thead><tbody>{audit.map(a=><tr key={a.id}><td>{date(a.at,true)}</td><td dir="ltr">{a.username}</td><td>{{login:'ورود',logout:'خروج',create:'ایجاد',update:'ویرایش',delete:'حذف',password_change:'تغییر رمز',settings_update:'تغییر تنظیمات',demo_load:'بارگذاری نمونه',demo_clear:'پاک‌سازی نمونه',csv_import:'ورود CSV',user_update:'تغییر کاربر',user_create:'ایجاد کاربر'}[a.action]||a.action}</td><td>{data.catalog[a.kind]?.label||a.kind||'—'}</td><td>{a.detail||'—'}</td></tr>)}</tbody></table></div>:<Empty/>}</section>}
    {tab==='password'&&<PasswordPanel notify={notify}/>}
    {userForm&&<UserEditor existing={userForm===true?undefined:userForm} roles={data.roles} onClose={closeUser} onSaved={async()=>{await fetchUsers();notify('حساب کاربری ذخیره شد.')}}/>}
    {confirm&&<Dialog title="پاک‌سازی داده‌های نمایشی" onClose={()=>setConfirm(false)}><div className="modal-body"><p>تمام رکوردهای دارای برچسب نمایشی حذف می‌شوند. اطلاعات واقعی و کاربران حفظ می‌شوند. اگر رکورد واقعی به نمونه‌ها مرتبط باشد، عملیات انجام نمی‌شود.</p></div><div className="modal-footer"><button className="button destructive" disabled={busy} onClick={()=>run(async()=>{await api('/demo/clear','POST');setConfirm(false)},'داده‌های نمایشی پاک شدند.')}>پاک‌سازی نمونه‌ها</button><button className="button" onClick={()=>setConfirm(false)}>انصراف</button></div></Dialog>}
  </>
}
function PasswordPanel({notify}:{notify:Notify}){
  const [old,setOld]=useState('');const [next,setNext]=useState('');const [repeat,setRepeat]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false)
  const save=async(e:React.SubmitEvent<HTMLFormElement>)=>{e.preventDefault();setError('');if(next!==repeat){setError('تکرار رمز جدید یکسان نیست.');return}setBusy(true);try{await api('/auth/password','POST',{current_password:old,new_password:next});setOld('');setNext('');setRepeat('');notify('رمز عبور تغییر کرد. سایر نشست‌ها بسته شدند.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <section className="card password-panel"><CardHead title="تغییر رمز عبور" subtitle="رمز جدید باید حداقل ۱۰ کاراکتر داشته باشد."/><form onSubmit={save}><div className="padded stack"><ErrorBox message={error}/>{[['رمز فعلی',old,setOld],['رمز جدید',next,setNext],['تکرار رمز جدید',repeat,setRepeat]].map(([title,val,set],i)=><div className="form-field" key={i}><label htmlFor={'pass-'+i}>{String(title)}</label><input id={'pass-'+i} type="password" dir="ltr" required autoComplete={i===0?'current-password':'new-password'} minLength={i===0?1:10} maxLength={256} value={String(val)} onChange={e=>(set as (v:string)=>void)(e.target.value)}/></div>)}</div><div className="modal-footer"><button className="button primary" disabled={busy}><Icon name="KeyRound" size={17}/>ذخیره رمز جدید</button></div></form></section>
}
function UserEditor({existing,roles,onClose,onSaved}:{existing?:User;roles:Record<string,string>;onClose:()=>void;onSaved:()=>Promise<void>}){
  const [value,setValue]=useState({name:existing?.name||'',username:existing?.username||'',role:existing?.role||'viewer',password:'',active:existing?!!existing.active:true});const [error,setError]=useState('');const [busy,setBusy]=useState(false)
  const save=async(e:React.SubmitEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setError('');try{await api('/users'+(existing?'/'+existing.id:''),existing?'PUT':'POST',{...value,password:value.password||null});await onSaved();onClose()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <Dialog title={existing?'ویرایش کاربر':'افزودن کاربر'} onClose={onClose}><form onSubmit={save}><div className="modal-body stack"><ErrorBox message={error}/>{[['name','نام کامل'],['username','نام کاربری'],['password',existing?'رمز جدید (اختیاری)':'رمز عبور']].map(([key,title])=><div className="form-field" key={key}><label htmlFor={'user-'+key}>{title}</label><input id={'user-'+key} type={key==='password'?'password':'text'} autoComplete={key==='password'?'new-password':'off'} required={key!=='password'||!existing} minLength={key==='password'?10:key==='username'?3:1} pattern={key==='username'?'[A-Za-z0-9_.-]+':undefined} dir={key==='name'?'rtl':'ltr'} value={String(value[key as keyof typeof value])} onChange={e=>setValue({...value,[key]:e.target.value})}/></div>)}<div className="form-field"><label htmlFor="user-role">نقش</label><select id="user-role" value={value.role} onChange={e=>setValue({...value,role:e.target.value})}>{Object.entries(roles).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></div><label className="check-label"><input type="checkbox" checked={value.active} onChange={e=>setValue({...value,active:e.target.checked})}/>حساب فعال</label></div><div className="modal-footer"><button className="button primary" disabled={busy}>ذخیره کاربر</button><button className="button" type="button" onClick={onClose}>انصراف</button></div></form></Dialog>
}
